// Curated country/region list (ISO 3166-1 English short name) for the
// registration form. Kept as plain data so it's easy to extend.
export const COUNTRIES: readonly string[] = [
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Singapore",
  "United Arab Emirates",
  "Saudi Arabia",
  "Germany",
  "France",
  "Netherlands",
  "Spain",
  "Italy",
  "Ireland",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Switzerland",
  "Belgium",
  "Portugal",
  "Poland",
  "Turkey",
  "Japan",
  "South Korea",
  "China",
  "Hong Kong",
  "Taiwan",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Thailand",
  "Vietnam",
  "Bangladesh",
  "Pakistan",
  "Sri Lanka",
  "Nepal",
  "Bhutan",
  "New Zealand",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Egypt",
  "Ghana",
  "Morocco",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Other",
] as const;

export const DEFAULT_COUNTRY = "India";
