// Dashboard-scoped virtual course catalog.
// Each entry maps to a persistent `courses` row via `slug` (created on demand
// by ensureCatalogCourse). Content (chapters/lessons) is generated by AI when
// the learner opens the course.

export type BoardEnum = "cbse" | "state_board" | "icse" | "cambridge" | "ib" | "nios" | "other";
export type DifficultyEnum = "beginner" | "intermediate" | "advanced";

export type CatalogCourse = {
  slug: string;
  title: string;
  subject: string;
  description: string;
  board: BoardEnum;
  class_min: number;
  class_max: number;
  difficulty: DifficultyEnum;
  estimated_hours: number;
  learning_objectives: string[];
};

export type CatalogCategory = {
  key: string;
  label: string;
  emoji: string;
  description: string;
  courses: CatalogCourse[];
};

export type CatalogScope = {
  role: "school" | "college" | "professional";
  title: string;
  description: string;
  categories: CatalogCategory[];
};

/* -------------------------------------------------------------------------- */
/* School (Classes 1–12)                                                       */
/* -------------------------------------------------------------------------- */

const SCHOOL_SUBJECTS_1_5 = [
  "English",
  "Mathematics",
  "Environmental Science (EVS)",
  "General Science",
  "Social Studies",
  "Computer Science",
  "General Knowledge",
];

const SCHOOL_SUBJECTS_6_10 = [
  "English",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "General Science",
  "Social Science",
  "History",
  "Geography",
  "Civics",
  "Economics",
  "Computer Science",
];

const SCHOOL_11_12: Record<string, string[]> = {
  Science: ["Physics", "Chemistry", "Mathematics", "Biology", "Computer Science", "English"],
  Commerce: [
    "Accountancy",
    "Business Studies",
    "Economics",
    "Commerce",
    "Mathematics",
    "Computer Applications",
    "English",
  ],
  Humanities: [
    "History",
    "Geography",
    "Political Science",
    "Economics",
    "Psychology",
    "Sociology",
    "English",
  ],
};

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/\([^)]*\)/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function schoolCourse(classNum: number, subject: string, stream?: string): CatalogCourse {
  const cls = `Class ${classNum}`;
  const label = stream ? `${cls} · ${stream}` : cls;
  return {
    slug: `nova-school-c${classNum}${stream ? "-" + slugify(stream) : ""}-${slugify(subject)}`,
    title: `${subject} — ${label}`,
    subject,
    description: `AI-personalized ${subject} for ${label}. Chapters, lessons, notes, MCQs, assignments, quizzes, mock tests, and revision — generated on demand.`,
    board: "cbse",
    class_min: classNum,
    class_max: classNum,
    difficulty: classNum <= 5 ? "beginner" : classNum <= 8 ? "beginner" : classNum <= 10 ? "intermediate" : "advanced",
    estimated_hours: classNum <= 5 ? 20 : classNum <= 10 ? 40 : 60,
    learning_objectives: [
      `Master the ${label} ${subject} syllabus`,
      "Practice with adaptive AI questions",
      "Track progress week by week",
    ],
  };
}

function buildSchoolCategories(): CatalogCategory[] {
  const cats: CatalogCategory[] = [];
  for (let c = 1; c <= 5; c++) {
    cats.push({
      key: `class-${c}`,
      label: `Class ${c}`,
      emoji: "🌱",
      description: `Foundation subjects for Class ${c}`,
      courses: SCHOOL_SUBJECTS_1_5.map((s) => schoolCourse(c, s)),
    });
  }
  for (let c = 6; c <= 10; c++) {
    cats.push({
      key: `class-${c}`,
      label: `Class ${c}`,
      emoji: c <= 8 ? "📗" : "📘",
      description: `Core subjects for Class ${c}`,
      courses: SCHOOL_SUBJECTS_6_10.map((s) => schoolCourse(c, s)),
    });
  }
  for (const c of [11, 12]) {
    for (const stream of Object.keys(SCHOOL_11_12)) {
      cats.push({
        key: `class-${c}-${slugify(stream)}`,
        label: `Class ${c} · ${stream}`,
        emoji: stream === "Science" ? "🔬" : stream === "Commerce" ? "📊" : "🏛️",
        description: `${stream} stream for Class ${c}`,
        courses: SCHOOL_11_12[stream].map((s) => schoolCourse(c, s, stream)),
      });
    }
  }
  return cats;
}

/* -------------------------------------------------------------------------- */
/* College                                                                     */
/* -------------------------------------------------------------------------- */

const COLLEGE_TRACKS: Array<{ key: string; label: string; emoji: string; description: string; courses: string[] }> = [
  {
    key: "cs-engineering",
    label: "Computer Science & Engineering",
    emoji: "💻",
    description: "Core CS fundamentals to industry-grade engineering",
    courses: [
      "Data Structures & Algorithms",
      "Operating Systems",
      "Database Management Systems",
      "Computer Networks",
      "Design & Analysis of Algorithms",
      "Object-Oriented Programming",
      "Software Engineering",
      "Compiler Design",
      "Theory of Computation",
      "System Design",
    ],
  },
  {
    key: "data-science-ai",
    label: "Data Science & AI",
    emoji: "🤖",
    description: "Statistics, ML, deep learning, and applied AI",
    courses: [
      "Python for Data Science",
      "Statistics & Probability",
      "Machine Learning",
      "Deep Learning",
      "Natural Language Processing",
      "Computer Vision",
      "Data Engineering",
      "MLOps",
    ],
  },
  {
    key: "electronics-communication",
    label: "Electronics & Communication",
    emoji: "📡",
    description: "Signals, circuits, VLSI, and communication systems",
    courses: [
      "Digital Electronics",
      "Signals & Systems",
      "Analog Electronics",
      "VLSI Design",
      "Communication Systems",
      "Embedded Systems",
      "Control Systems",
    ],
  },
  {
    key: "mechanical",
    label: "Mechanical Engineering",
    emoji: "⚙️",
    description: "Thermodynamics, mechanics, manufacturing",
    courses: [
      "Engineering Mechanics",
      "Thermodynamics",
      "Fluid Mechanics",
      "Mechanics of Materials",
      "Manufacturing Processes",
      "Machine Design",
      "CAD/CAM",
    ],
  },
  {
    key: "civil",
    label: "Civil Engineering",
    emoji: "🏗️",
    description: "Structural, geotech, environmental",
    courses: [
      "Structural Analysis",
      "Geotechnical Engineering",
      "Transportation Engineering",
      "Surveying",
      "Environmental Engineering",
      "Construction Management",
    ],
  },
  {
    key: "business-management",
    label: "Business & Management",
    emoji: "📈",
    description: "MBA-track fundamentals and analytics",
    courses: [
      "Financial Accounting",
      "Managerial Economics",
      "Marketing Management",
      "Human Resource Management",
      "Operations Management",
      "Business Analytics",
      "Corporate Finance",
      "Strategic Management",
    ],
  },
  {
    key: "design",
    label: "Design",
    emoji: "🎨",
    description: "UX, UI, interaction, and design thinking",
    courses: [
      "Design Thinking",
      "UX Research",
      "UI Design Fundamentals",
      "Interaction Design",
      "Visual Design & Typography",
      "Prototyping with Figma",
    ],
  },
];

function collegeCourse(track: { key: string; label: string }, title: string): CatalogCourse {
  return {
    slug: `nova-college-${track.key}-${slugify(title)}`,
    title,
    subject: title,
    description: `${title} for ${track.label} — AI-generated curriculum with chapters, lessons, practice, and assessments.`,
    board: "other",
    class_min: 13,
    class_max: 16,
    difficulty: "intermediate",
    estimated_hours: 60,
    learning_objectives: [
      `Build strong ${title} fundamentals`,
      "Apply concepts through worked examples and problems",
      "Prepare for exams and interviews with adaptive assessments",
    ],
  };
}

function buildCollegeCategories(): CatalogCategory[] {
  return COLLEGE_TRACKS.map((t) => ({
    key: t.key,
    label: t.label,
    emoji: t.emoji,
    description: t.description,
    courses: t.courses.map((c) => collegeCourse(t, c)),
  }));
}

/* -------------------------------------------------------------------------- */
/* Professional                                                                */
/* -------------------------------------------------------------------------- */

const PRO_TRACKS: Array<{ key: string; label: string; emoji: string; description: string; courses: string[] }> = [
  {
    key: "web-mobile",
    label: "Web & Mobile Development",
    emoji: "🌐",
    description: "Modern full-stack and cross-platform mobile",
    courses: [
      "React & Modern Frontend",
      "Next.js Full-Stack",
      "TypeScript Deep Dive",
      "Node.js & APIs",
      "React Native",
      "Flutter for Mobile",
      "Web Performance",
    ],
  },
  {
    key: "cloud-devops",
    label: "Cloud & DevOps",
    emoji: "☁️",
    description: "Ship reliably at scale",
    courses: [
      "AWS Fundamentals",
      "Azure Fundamentals",
      "Google Cloud Platform",
      "Docker & Containers",
      "Kubernetes in Production",
      "Terraform & IaC",
      "CI/CD Pipelines",
      "Site Reliability Engineering",
    ],
  },
  {
    key: "data-ai",
    label: "Data & AI",
    emoji: "🧠",
    description: "Applied data, ML, and Generative AI",
    courses: [
      "SQL for Analytics",
      "Python for Data",
      "Applied Machine Learning",
      "Generative AI & LLMs",
      "Prompt Engineering",
      "LangChain & RAG",
      "MLOps in Practice",
    ],
  },
  {
    key: "cybersecurity",
    label: "Cybersecurity",
    emoji: "🛡️",
    description: "Defensive and offensive security",
    courses: [
      "Network Security",
      "Ethical Hacking",
      "Cloud Security",
      "Application Security",
      "SIEM & Blue Team",
      "GRC & Compliance",
    ],
  },
  {
    key: "product-design",
    label: "Product & Design",
    emoji: "🧭",
    description: "Ship user-loved products",
    courses: [
      "Product Management Fundamentals",
      "UX Research Methods",
      "Figma for Product Teams",
      "Prototyping & Testing",
      "Product Analytics",
    ],
  },
  {
    key: "leadership",
    label: "Leadership & Management",
    emoji: "🚀",
    description: "Lead teams and outcomes",
    courses: [
      "People Management",
      "Effective Communication",
      "Strategy for Managers",
      "Negotiation",
      "Executive Presence",
    ],
  },
  {
    key: "marketing",
    label: "Digital Marketing",
    emoji: "📣",
    description: "Growth, content, and analytics",
    courses: [
      "SEO Fundamentals",
      "Content Marketing",
      "Performance Marketing",
      "Marketing Analytics",
      "Email & Lifecycle",
    ],
  },
];

function proCourse(track: { key: string; label: string }, title: string): CatalogCourse {
  return {
    slug: `nova-pro-${track.key}-${slugify(title)}`,
    title,
    subject: title,
    description: `${title} — hands-on upskilling with AI-generated modules, projects, and assessments.`,
    board: "other",
    class_min: 20,
    class_max: 20,
    difficulty: "intermediate",
    estimated_hours: 30,
    learning_objectives: [
      `Ship real ${title} outcomes at work`,
      "Practice with scenario-based exercises",
      "Validate mastery with adaptive assessments",
    ],
  };
}

function buildProCategories(): CatalogCategory[] {
  return PRO_TRACKS.map((t) => ({
    key: t.key,
    label: t.label,
    emoji: t.emoji,
    description: t.description,
    courses: t.courses.map((c) => proCourse(t, c)),
  }));
}

/* -------------------------------------------------------------------------- */
/* Public API                                                                  */
/* -------------------------------------------------------------------------- */

export const SCHOOL_CATALOG: CatalogScope = {
  role: "school",
  title: "School Learning",
  description: "Class-wise subjects for Classes 1–12",
  categories: buildSchoolCategories(),
};

export const COLLEGE_CATALOG: CatalogScope = {
  role: "college",
  title: "College Learning",
  description: "Tracks aligned to Indian & global undergraduate programs",
  categories: buildCollegeCategories(),
};

export const PRO_CATALOG: CatalogScope = {
  role: "professional",
  title: "Professional Upskilling",
  description: "In-demand tracks curated for working professionals",
  categories: buildProCategories(),
};

export const CATALOG_BY_ROLE = {
  student: SCHOOL_CATALOG,
  college_student: COLLEGE_CATALOG,
  professional: PRO_CATALOG,
} as const;

export function findCatalogCourse(slug: string): CatalogCourse | null {
  for (const scope of [SCHOOL_CATALOG, COLLEGE_CATALOG, PRO_CATALOG]) {
    for (const cat of scope.categories) {
      const hit = cat.courses.find((c) => c.slug === slug);
      if (hit) return hit;
    }
  }
  return null;
}
