// Dashboard-scoped virtual course catalog.
// Each entry maps to a persistent `courses` row via `slug` (created on demand
// by ensureCatalogCourse). Content (chapters/lessons) is generated by AI when
// the learner opens the course.

export type BoardEnum = "cbse" | "state_board" | "icse" | "cambridge" | "ib" | "nios" | "other";
export type DifficultyEnum = "beginner" | "intermediate" | "advanced";

export type CatalogCourse = {
  slug: string;
  title: string;
  subject: string;
  description: string;
  board: BoardEnum;
  class_min: number;
  class_max: number;
  difficulty: DifficultyEnum;
  estimated_hours: number;
  learning_objectives: string[];
};

export type CatalogCategory = {
  key: string;
  label: string;
  emoji: string;
  description: string;
  courses: CatalogCourse[];
};

export type CatalogScope = {
  role: "school" | "college" | "professional";
  title: string;
  description: string;
  categories: CatalogCategory[];
};

/* -------------------------------------------------------------------------- */
/* School (Classes 1–12)                                                       */
/* -------------------------------------------------------------------------- */

const SCHOOL_SUBJECTS_1_5 = [
  "English",
  "Mathematics",
  "Environmental Science (EVS)",
  "General Science",
  "Social Studies",
  "Computer Science",
  "General Knowledge",
];

const SCHOOL_SUBJECTS_6_10 = [
  "English",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "General Science",
  "Social Science",
  "History",
  "Geography",
  "Civics",
  "Economics",
  "Computer Science",
];

const SCHOOL_11_12: Record<string, string[]> = {
  Science: ["Physics", "Chemistry", "Mathematics", "Biology", "Computer Science", "English"],
  Commerce: [
    "Accountancy",
    "Business Studies",
    "Economics",
    "Commerce",
    "Mathematics",
    "Computer Applications",
    "English",
  ],
  Humanities: [
    "History",
    "Geography",
    "Political Science",
    "Economics",
    "Psychology",
    "Sociology",
    "English",
  ],
};

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/\([^)]*\)/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function schoolCourse(classNum: number, subject: string, stream?: string): CatalogCourse {
  const cls = `Class ${classNum}`;
  const label = stream ? `${cls} · ${stream}` : cls;
  return {
    slug: `nova-school-c${classNum}${stream ? "-" + slugify(stream) : ""}-${slugify(subject)}`,
    title: `${subject} — ${label}`,
    subject,
    description: `AI-personalized ${subject} for ${label}. Chapters, lessons, notes, MCQs, assignments, quizzes, mock tests, and revision — generated on demand.`,
    board: "cbse",
    class_min: classNum,
    class_max: classNum,
    difficulty: classNum <= 5 ? "beginner" : classNum <= 8 ? "beginner" : classNum <= 10 ? "intermediate" : "advanced",
    estimated_hours: classNum <= 5 ? 20 : classNum <= 10 ? 40 : 60,
    learning_objectives: [
      `Master the ${label} ${subject} syllabus`,
      "Practice with adaptive AI questions",
      "Track progress week by week",
    ],
  };
}

function buildSchoolCategories(): CatalogCategory[] {
  const cats: CatalogCategory[] = [];
  for (let c = 1; c <= 5; c++) {
    cats.push({
      key: `class-${c}`,
      label: `Class ${c}`,
      emoji: "🌱",
      description: `Foundation subjects for Class ${c}`,
      courses: SCHOOL_SUBJECTS_1_5.map((s) => schoolCourse(c, s)),
    });
  }
  for (let c = 6; c <= 10; c++) {
    cats.push({
      key: `class-${c}`,
      label: `Class ${c}`,
      emoji: c <= 8 ? "📗" : "📘",
      description: `Core subjects for Class ${c}`,
      courses: SCHOOL_SUBJECTS_6_10.map((s) => schoolCourse(c, s)),
    });
  }
  for (const c of [11, 12]) {
    for (const stream of Object.keys(SCHOOL_11_12)) {
      cats.push({
        key: `class-${c}-${slugify(stream)}`,
        label: `Class ${c} · ${stream}`,
        emoji: stream === "Science" ? "🔬" : stream === "Commerce" ? "📊" : "🏛️",
        description: `${stream} stream for Class ${c}`,
        courses: SCHOOL_11_12[stream].map((s) => schoolCourse(c, s, stream)),
      });
    }
  }
  return cats;
}

/* -------------------------------------------------------------------------- */
/* College                                                                     */
/* -------------------------------------------------------------------------- */

const COLLEGE_TRACKS: Array<{ key: string; label: string; emoji: string; description: string; courses: string[] }> = [
  {
    key: "programming-languages",
    label: "Programming Languages",
    emoji: "💻",
    description: "Core languages every college student should master",
    courses: ["C", "C++", "Java", "Python", "JavaScript", "TypeScript", "C#", "PHP", "Go", "Rust"],
  },
  {
    key: "web-development",
    label: "Web Development",
    emoji: "🌐",
    description: "Frontend, backend, and full-stack fundamentals",
    courses: [
      "HTML",
      "CSS",
      "Bootstrap",
      "Tailwind CSS",
      "React",
      "Angular",
      "Vue.js",
      "Node.js",
      "Express.js",
      "Next.js",
    ],
  },
  {
    key: "databases",
    label: "Databases",
    emoji: "🗄️",
    description: "Relational, NoSQL, and cloud databases",
    courses: ["SQL", "MySQL", "PostgreSQL", "MongoDB", "Firebase"],
  },
  {
    key: "cs-core",
    label: "Computer Science Subjects",
    emoji: "🎓",
    description: "Semester-aligned CS foundations",
    courses: [
      "Data Structures",
      "Algorithms",
      "Database Management Systems",
      "Operating Systems",
      "Computer Networks",
      "Software Engineering",
      "Compiler Design",
      "Computer Architecture",
      "Theory of Computation",
      "System Design",
    ],
  },
  {
    key: "ai-ml",
    label: "Artificial Intelligence",
    emoji: "🤖",
    description: "From AI basics to modern generative systems",
    courses: [
      "AI Fundamentals",
      "Machine Learning",
      "Deep Learning",
      "Generative AI",
      "Prompt Engineering",
      "Natural Language Processing",
      "Computer Vision",
    ],
  },
  {
    key: "cloud-devops",
    label: "Cloud & DevOps",
    emoji: "☁️",
    description: "Version control, containers, and cloud platforms",
    courses: ["Git", "GitHub", "Docker", "Kubernetes", "AWS", "Azure", "Google Cloud", "CI/CD"],
  },
  {
    key: "cybersecurity",
    label: "Cyber Security",
    emoji: "🛡️",
    description: "Defensive and offensive security fundamentals",
    courses: ["Cyber Security", "Ethical Hacking", "Network Security", "Application Security"],
  },
  {
    key: "data-science",
    label: "Data Science",
    emoji: "📊",
    description: "Analytics, statistics, and applied ML",
    courses: [
      "Python for Data Science",
      "Statistics & Probability",
      "Data Analytics",
      "Data Visualization",
      "SQL for Analytics",
      "Big Data Fundamentals",
    ],
  },
  {
    key: "design",
    label: "UI/UX Design",
    emoji: "🎨",
    description: "Research, interaction, and visual design",
    courses: [
      "Design Thinking",
      "UX Research",
      "UI Design Fundamentals",
      "Interaction Design",
      "Prototyping with Figma",
    ],
  },
  {
    key: "mobile",
    label: "Mobile Development",
    emoji: "📱",
    description: "Cross-platform and native mobile apps",
    courses: ["Android Development", "Kotlin", "Swift (iOS)", "Flutter", "React Native"],
  },
  {
    key: "placement",
    label: "Placement Preparation",
    emoji: "🎯",
    description: "Aptitude, interviews, and campus-ready skills",
    courses: [
      "Quantitative Aptitude",
      "Logical Reasoning",
      "Verbal Ability",
      "Interview Preparation",
      "Group Discussion",
      "Resume Building",
      "HR Interview",
    ],
  },
  {
    key: "academic",
    label: "Research & Academic Writing",
    emoji: "📝",
    description: "Papers, citations, and research methodology",
    courses: [
      "Research Methodology",
      "Academic Writing",
      "Literature Review",
      "Referencing & Citations",
      "Publishing Research Papers",
    ],
  },
];


function collegeCourse(track: { key: string; label: string }, title: string): CatalogCourse {
  return {
    slug: `nova-college-${track.key}-${slugify(title)}`,
    title,
    subject: title,
    description: `${title} for ${track.label} — AI-generated curriculum with chapters, lessons, practice, and assessments.`,
    board: "other",
    class_min: 13,
    class_max: 16,
    difficulty: "intermediate",
    estimated_hours: 60,
    learning_objectives: [
      `Build strong ${title} fundamentals`,
      "Apply concepts through worked examples and problems",
      "Prepare for exams and interviews with adaptive assessments",
    ],
  };
}

function buildCollegeCategories(): CatalogCategory[] {
  return COLLEGE_TRACKS.map((t) => ({
    key: t.key,
    label: t.label,
    emoji: t.emoji,
    description: t.description,
    courses: t.courses.map((c) => collegeCourse(t, c)),
  }));
}

/* -------------------------------------------------------------------------- */
/* Professional                                                                */
/* -------------------------------------------------------------------------- */

const PRO_TRACKS: Array<{ key: string; label: string; emoji: string; description: string; courses: string[] }> = [
  {
    key: "generative-ai",
    label: "Generative AI & AI Agents",
    emoji: "🤖",
    description: "LLMs, agents, and production GenAI",
    courses: [
      "Generative AI",
      "AI Agents",
      "Prompt Engineering",
      "LangChain & RAG",
      "LLM Application Development",
      "AI Product Strategy",
    ],
  },
  {
    key: "full-stack",
    label: "Full Stack Development",
    emoji: "🌐",
    description: "Modern full-stack engineering",
    courses: [
      "MERN Stack",
      "Next.js Full-Stack",
      "React & Modern Frontend",
      "TypeScript Deep Dive",
      "Node.js & APIs",
      "GraphQL",
      "Web Performance",
    ],
  },
  {
    key: "data-analytics",
    label: "Data Analytics",
    emoji: "📊",
    description: "Analytics and BI for decision makers",
    courses: [
      "Data Analytics",
      "Power BI",
      "Excel for Professionals",
      "SQL for Analytics",
      "Tableau",
      "Business Analytics",
    ],
  },
  {
    key: "cloud",
    label: "Cloud Computing",
    emoji: "☁️",
    description: "Cloud fundamentals and certification tracks",
    courses: [
      "AWS Fundamentals",
      "Azure Fundamentals",
      "Google Cloud Platform",
      "Cloud Architecture",
      "Serverless in Production",
    ],
  },
  {
    key: "devops",
    label: "DevOps",
    emoji: "⚙️",
    description: "Ship reliably at scale",
    courses: [
      "Docker & Containers",
      "Kubernetes in Production",
      "CI/CD Pipelines",
      "Terraform & IaC",
      "Site Reliability Engineering",
      "Observability & Monitoring",
    ],
  },
  {
    key: "cybersecurity",
    label: "Cyber Security",
    emoji: "🛡️",
    description: "Defensive and offensive security",
    courses: [
      "Network Security",
      "Application Security",
      "Cloud Security",
      "Ethical Hacking",
      "SIEM & Blue Team",
      "GRC & Compliance",
    ],
  },
  {
    key: "product-design",
    label: "Product & UI/UX",
    emoji: "🧭",
    description: "Ship user-loved products",
    courses: [
      "Product Management Fundamentals",
      "UX Research Methods",
      "UI Design Fundamentals",
      "Figma for Product Teams",
      "Prototyping & Testing",
      "Product Analytics",
    ],
  },
  {
    key: "leadership",
    label: "Leadership & Communication",
    emoji: "🚀",
    description: "Lead people and outcomes",
    courses: [
      "People Management",
      "Effective Communication",
      "Executive Presence",
      "Negotiation",
      "Strategy for Managers",
      "Public Speaking",
    ],
  },
  {
    key: "agile",
    label: "Agile & Scrum",
    emoji: "🔁",
    description: "Delivery frameworks for modern teams",
    courses: [
      "Agile Fundamentals",
      "Scrum Master Prep",
      "Product Owner Prep",
      "Kanban in Practice",
      "SAFe Overview",
    ],
  },
  {
    key: "entrepreneurship",
    label: "Entrepreneurship",
    emoji: "💡",
    description: "From idea to funded venture",
    courses: [
      "Startup Fundamentals",
      "Business Model Canvas",
      "Fundraising & Pitching",
      "Go-to-Market Strategy",
      "Founder Finance",
    ],
  },
  {
    key: "marketing",
    label: "Digital Marketing",
    emoji: "📣",
    description: "Growth, content, and analytics",
    courses: [
      "SEO Fundamentals",
      "Content Marketing",
      "Performance Marketing",
      "Marketing Analytics",
      "Email & Lifecycle",
      "Social Media Strategy",
    ],
  },
  {
    key: "finance",
    label: "Finance for Professionals",
    emoji: "💰",
    description: "Financial literacy and analysis",
    courses: [
      "Financial Statements 101",
      "Corporate Finance",
      "Personal Finance",
      "Investing Fundamentals",
      "Financial Modeling in Excel",
    ],
  },
];


function proCourse(track: { key: string; label: string }, title: string): CatalogCourse {
  return {
    slug: `nova-pro-${track.key}-${slugify(title)}`,
    title,
    subject: title,
    description: `${title} — hands-on upskilling with AI-generated modules, projects, and assessments.`,
    board: "other",
    class_min: 20,
    class_max: 20,
    difficulty: "intermediate",
    estimated_hours: 30,
    learning_objectives: [
      `Ship real ${title} outcomes at work`,
      "Practice with scenario-based exercises",
      "Validate mastery with adaptive assessments",
    ],
  };
}

function buildProCategories(): CatalogCategory[] {
  return PRO_TRACKS.map((t) => ({
    key: t.key,
    label: t.label,
    emoji: t.emoji,
    description: t.description,
    courses: t.courses.map((c) => proCourse(t, c)),
  }));
}

/* -------------------------------------------------------------------------- */
/* Public API                                                                  */
/* -------------------------------------------------------------------------- */

export const SCHOOL_CATALOG: CatalogScope = {
  role: "school",
  title: "School Learning",
  description: "Class-wise subjects for Classes 1–12",
  categories: buildSchoolCategories(),
};

export const COLLEGE_CATALOG: CatalogScope = {
  role: "college",
  title: "College Learning",
  description: "Tracks aligned to Indian & global undergraduate programs",
  categories: buildCollegeCategories(),
};

export const PRO_CATALOG: CatalogScope = {
  role: "professional",
  title: "Professional Upskilling",
  description: "In-demand tracks curated for working professionals",
  categories: buildProCategories(),
};

export const CATALOG_BY_ROLE = {
  student: SCHOOL_CATALOG,
  college_student: COLLEGE_CATALOG,
  professional: PRO_CATALOG,
} as const;

export function findCatalogCourse(slug: string): CatalogCourse | null {
  for (const scope of [SCHOOL_CATALOG, COLLEGE_CATALOG, PRO_CATALOG]) {
    for (const cat of scope.categories) {
      const hit = cat.courses.find((c) => c.slug === slug);
      if (hit) return hit;
    }
  }
  return null;
}
