import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { ClipboardList, Sparkles, CheckCircle2, PlayCircle, Clock } from "lucide-react";
import { DashboardHeader } from "@/components/dashboard/DashboardShared";
import { SectionHeader, DashCard, EmptyState } from "@/components/dashboard/DashboardWidgets";
import { RoleGate } from "@/components/auth/RoleGate";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import {
  ASSESSMENT_SUBJECTS,
  boardLabel,
  subjectsForClass,
} from "@/lib/syllabus/catalog";
import {
  listAiWeeklyAttempts,
  startAiWeeklyAssessment,
} from "@/lib/ai/ai-weekly.functions";

export const Route = createFileRoute("/_dashboard/dashboard/student/assessments")({
  component: AssessmentsPage,
});

function AssessmentsPage() {
  const navigate = useNavigate();
  const qc = useQueryClient();
  const list = useServerFn(listAiWeeklyAttempts);
  const start = useServerFn(startAiWeeklyAssessment);
  const [selected, setSelected] = useState<Set<string>>(new Set());

  const { data: profile } = useQuery({
    queryKey: ["me", "student_profile", "assessments"],
    queryFn: async () => {
      const { data: u } = await supabase.auth.getUser();
      if (!u.user) return null;
      const { data } = await supabase
        .from("student_profiles")
        .select("current_class, board")
        .eq("user_id", u.user.id)
        .maybeSingle();
      return data as { current_class: number | null; board: string | null } | null;
    },
    staleTime: 60_000,
  });

  const { data: attempts } = useQuery({
    queryKey: ["me", "ai-weekly-attempts"],
    queryFn: () => list(),
    staleTime: 10_000,
  });

  const eligibleSubjects = useMemo(() => {
    const forClass = subjectsForClass(profile?.current_class);
    const allowed = new Set(ASSESSMENT_SUBJECTS as readonly string[]);
    const filtered = forClass.filter((s) => allowed.has(s));
    return filtered.length > 0 ? filtered : (ASSESSMENT_SUBJECTS as readonly string[]).slice();
  }, [profile?.current_class]);

  const toggle = (s: string) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(s)) next.delete(s);
      else next.add(s);
      return next;
    });
  };

  const startMutation = useMutation({
    mutationFn: async (subjects: string[]) => start({ data: { subjects } }),
    onSuccess: async (res) => {
      await qc.invalidateQueries({ queryKey: ["me", "ai-weekly-attempts"] });
      toast.success("Fresh assessment generated");
      navigate({
        to: "/dashboard/student/assessments/$assessmentId",
        params: { assessmentId: res.attemptId },
      });
    },
    onError: (e: Error) => toast.error(e.message ?? "Could not generate assessment"),
  });

  const canStart =
    !!profile?.board &&
    !!profile?.current_class &&
    profile.current_class >= 6 &&
    profile.current_class <= 12;

  const handleStart = () => {
    if (!canStart) {
      toast.error("Weekly assessments are for classes 6–12. Complete your syllabus first.");
      return;
    }
    if (selected.size === 0) {
      toast.error("Select at least one subject.");
      return;
    }
    startMutation.mutate(Array.from(selected));
  };

  const rows = attempts ?? [];

  return (
    <RoleGate allow={["student"]}>
      <DashboardHeader
        title="AI Weekly Assessments"
        description={
          profile?.current_class
            ? `Class ${profile.current_class} · ${boardLabel(profile.board)} · 5 fresh AI-generated questions per subject`
            : "Personalised AI assessments generated fresh every attempt"
        }
      />

      <DashCard className="mb-8">
        <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
          <div className="flex-1">
            <p className="text-xs font-semibold uppercase tracking-wider text-primary">
              <Sparkles className="mr-1 inline h-3.5 w-3.5" /> Start a fresh assessment
            </p>
            <h3 className="mt-1 text-lg font-semibold">
              Pick subjects for your Class {profile?.current_class ?? "—"} weekly test
            </h3>
            <p className="text-sm text-muted-foreground">
              5 questions per subject · MCQ, fill-in, true/false, match, short answer, numerical, assertion-reason
              {(profile?.current_class ?? 0) >= 6 ? ", programming (CS)" : ""}. Every attempt is regenerated by AI.
            </p>
          </div>
        </div>

        <div className="mt-5 flex flex-wrap gap-2">
          {eligibleSubjects.map((s) => {
            const active = selected.has(s);
            return (
              <button
                type="button"
                key={s}
                onClick={() => toggle(s)}
                className={`flex items-center gap-2 rounded-full border px-3 py-1.5 text-sm transition ${
                  active
                    ? "border-primary bg-primary/10 text-primary"
                    : "border-border/60 hover:border-primary/40"
                }`}
              >
                <Checkbox checked={active} className="pointer-events-none h-4 w-4" />
                {s}
              </button>
            );
          })}
        </div>

        <div className="mt-5 flex items-center justify-between gap-3">
          <p className="text-xs text-muted-foreground">
            {selected.size === 0
              ? "No subjects selected"
              : `${selected.size} subject${selected.size === 1 ? "" : "s"} · ${selected.size * 5} questions`}
          </p>
          <Button onClick={handleStart} disabled={startMutation.isPending}>
            {startMutation.isPending ? "Generating fresh questions…" : "Generate & start"}
          </Button>
        </div>
      </DashCard>

      <section>
        <SectionHeader title="Assessment history" />
        {rows.length === 0 ? (
          <EmptyState
            icon={<ClipboardList className="h-5 w-5" />}
            title="No attempts yet"
            description="Pick your subjects above and start your first fresh AI assessment."
          />
        ) : (
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {rows.map((a) => {
              const done = !!a.submitted_at;
              const pct = done && Number(a.max_score) > 0
                ? Math.round((Number(a.score) / Number(a.max_score)) * 100)
                : null;
              return (
                <Link
                  key={a.id}
                  to="/dashboard/student/assessments/$assessmentId"
                  params={{ assessmentId: a.id }}
                  className="block rounded-2xl border border-border/60 bg-card p-5 shadow-card transition hover:border-primary/40"
                >
                  <div className="mb-3 flex items-center justify-between">
                    <div className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary">
                      {done ? <CheckCircle2 className="h-5 w-5" /> : <PlayCircle className="h-5 w-5" />}
                    </div>
                    <span className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                      Week of {a.week_start}
                    </span>
                  </div>
                  <p className="text-xs font-medium uppercase tracking-wider text-primary">
                    {boardLabel(a.board)} · Class {a.class_level}
                  </p>
                  <div className="mt-1 flex flex-wrap gap-1">
                    {(a.subjects ?? []).slice(0, 4).map((s: string) => (
                      <Badge key={s} variant="secondary" className="text-[10px]">{s}</Badge>
                    ))}
                    {(a.subjects ?? []).length > 4 && (
                      <Badge variant="secondary" className="text-[10px]">+{(a.subjects ?? []).length - 4}</Badge>
                    )}
                  </div>
                  <p className="mt-3 text-sm">
                    {done ? (
                      <span className="font-semibold text-primary">
                        Score {a.score}/{a.max_score} · {pct}%
                      </span>
                    ) : (
                      <span className="text-muted-foreground">In progress…</span>
                    )}
                  </p>
                  {done && a.time_taken_seconds != null && (
                    <p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground">
                      <Clock className="h-3 w-3" />
                      {Math.floor(a.time_taken_seconds / 60)}m {a.time_taken_seconds % 60}s
                    </p>
                  )}
                  <p className="mt-3 text-xs font-semibold text-primary">
                    {done ? "Review results →" : "Continue attempt →"}
                  </p>
                </Link>
              );
            })}
          </div>
        )}
      </section>
    </RoleGate>
  );
}
