import { createFileRoute } from "@tanstack/react-router";
import { Sparkles } from "lucide-react";
import { ReaderShell, Section, Figure, Callout, FAQItem, Code, References, type ReaderResource, type TocItem } from "@/components/resources/ReaderShell";

const RESOURCE: ReaderResource = {
  id: "dl-real-world-case-study",
  title: "Deep Learning — Real-world Case Study",
  category: "AI & Data",
  difficulty: "Intermediate",
  readingTime: "17 min",
  pages: 29,
  lastUpdated: "January 2026",
  tags: ["Deep Learning", "DL", "PyTorch"],
  heroImage: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1800&q=80",
  heroSubtitle:
    "A production Deep Learning case study — from stakeholder analysis and dataset curation to PyTorch model design, deployment, monitoring, and measurable business impact.",
};

const TOC: TocItem[] = [
  { id: "company", label: "1. Company Overview" },
  { id: "problem", label: "2. Business Problem" },
  { id: "objectives", label: "3. Project Objectives" },
  { id: "requirements", label: "4. Requirement Analysis" },
  { id: "dataset", label: "5. Dataset Collection" },
  { id: "prep", label: "6. Data Preparation" },
  { id: "architecture", label: "7. Model Architecture" },
  { id: "training", label: "8. Training Strategy" },
  { id: "system", label: "9. System Architecture" },
  { id: "deployment", label: "10. Deployment Pipeline" },
  { id: "monitoring", label: "11. Monitoring & Maintenance" },
  { id: "performance", label: "12. Performance Evaluation" },
  { id: "business", label: "13. Business Outcomes" },
  { id: "lessons", label: "14. Lessons Learned" },
  { id: "future", label: "15. Future Enhancements" },
  { id: "review", label: "Real-world Review" },
  { id: "summary", label: "Summary & Key Takeaways" },
  { id: "faqs", label: "FAQ" },
  { id: "glossary", label: "Glossary" },
  { id: "references", label: "References" },
  { id: "disclaimer", label: "Disclaimer" },
];

const RELATED = [
  { title: "Deep Learning — Best Practices", tag: "AI & Data", time: "15 min" },
  { title: "Deep Learning — Learning Roadmap", tag: "AI & Data", time: "8 min" },
  { title: "Deep Learning — Reference Guide", tag: "AI & Data", time: "38 min" },
];

export const Route = createFileRoute("/_marketing/resources/read/dl-real-world-case-study")({
  head: () => ({
    meta: [
      { title: `${RESOURCE.title} | EduNova AI` },
      { name: "description", content: RESOURCE.heroSubtitle },
      { property: "og:title", content: `${RESOURCE.title} | EduNova AI` },
      { property: "og:description", content: RESOURCE.heroSubtitle },
      { property: "og:image", content: RESOURCE.heroImage },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: DLCaseStudyPage,
});

function DLCaseStudyPage() {
  return (
    <ReaderShell resource={RESOURCE} toc={TOC} related={RELATED}>
      <Section id="company" title="1. Company Overview">
        <p>
          NovaRetail is a mid-market e-commerce company operating across 14 countries with roughly
          9 million monthly active users. Their catalogue contains 1.4M SKUs across fashion, home,
          and electronics. In 2024, leadership committed to a Deep Learning initiative to replace
          brittle rule-based systems in personalisation, search, and inventory demand forecasting.
        </p>
        <ul className="list-disc space-y-1 pl-5">
          <li><strong>Industry:</strong> Consumer e-commerce.</li>
          <li><strong>Team:</strong> 6 ML engineers, 3 data engineers, 2 SREs, 1 product lead.</li>
          <li><strong>Stack:</strong> PyTorch 2.x, Ray, Feast, Triton Inference Server, Kubernetes.</li>
        </ul>
      </Section>

      <Section id="problem" title="2. Business Problem">
        <Callout tone="warning" title="Pain point">
          Product recommendations were generated by a hand-tuned collaborative filter refreshed
          nightly. CTR had plateaued at 3.1% for eight quarters and conversion on the recommender
          surface trailed the site average by 22%.
        </Callout>
        <p>Three symptoms surfaced simultaneously:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Cold-start failure — new items got no meaningful exposure for 7+ days.</li>
          <li>Session incoherence — the model ignored intra-session intent shifts.</li>
          <li>Long tail collapse — 84% of impressions concentrated on the top 5% of SKUs.</li>
        </ul>
      </Section>

      <Section id="objectives" title="3. Project Objectives">
        <ul className="list-disc space-y-1 pl-5">
          <li>Ship a Deep Learning recommender lifting CTR by ≥15% and revenue-per-visit by ≥8%.</li>
          <li>Support cold-start ranking within 30 minutes of catalogue ingest.</li>
          <li>Serve p99 latency under 90ms at 12k requests/second at peak.</li>
          <li>Maintain fairness across long-tail categories via exposure guardrails.</li>
        </ul>
      </Section>

      <Section id="requirements" title="4. Requirement Analysis">
        <p><strong>Stakeholders:</strong> merchandising, product, SRE, legal (GDPR), and finance.</p>
        <p>
          Requirement gathering happened over four workshops. Legal established that only hashed
          user IDs and behavioural events could be modelled; PII would never enter training data.
          SRE mandated horizontal scalability, blue-green deploys, and a rollback path under
          three minutes.
        </p>
      </Section>

      <Section id="dataset" title="5. Dataset Collection">
        <p>
          14 months of clickstream (impressions, clicks, add-to-cart, purchases), catalogue
          metadata (title, description, taxonomy, price, images), and merchandising signals
          (badges, promotions). Roughly <strong>4.8B events</strong> and <strong>1.4M items</strong>.
        </p>
        <Figure src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1400&q=80" caption="Figure 1 — Dataset overview: clickstream + catalogue metadata + merchandising signals feeding a shared feature store." />
      </Section>

      <Section id="prep" title="6. Data Preparation">
        <p>Feature engineering pipelines were consolidated in Feast with three views:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li><strong>User features:</strong> rolling engagement counts, embeddings of recent categories, freshness decay.</li>
          <li><strong>Item features:</strong> price percentile, availability, image CLIP embeddings, title/desc encoder embeddings.</li>
          <li><strong>Context features:</strong> device, hour, referrer, promo state.</li>
        </ul>
        <Code>{`# Two-tower features are precomputed nightly and streamed hot-path from Feast
user_features = fs.get_online_features(entity_rows=[{"user_id": uid}], features=USER_VIEW)
item_features = fs.get_online_features(entity_rows=[{"item_id": iid} for iid in candidates], features=ITEM_VIEW)`}</Code>
      </Section>

      <Section id="architecture" title="7. Model Architecture">
        <p>
          A <strong>two-tower retrieval</strong> model with a shared 128-dim embedding space
          feeds a <strong>cross-attention ranker</strong>. Retrieval runs ANN over a FAISS index;
          the ranker re-orders the top 500 candidates.
        </p>
        <Code>{`class TwoTower(nn.Module):
    def __init__(self, d=128):
        super().__init__()
        self.user_encoder = nn.Sequential(
            nn.Linear(USER_DIM, 512), nn.GELU(),
            nn.Linear(512, d),
        )
        self.item_encoder = nn.Sequential(
            nn.Linear(ITEM_DIM, 512), nn.GELU(),
            nn.Linear(512, d),
        )

    def forward(self, u, i):
        u = F.normalize(self.user_encoder(u), dim=-1)
        i = F.normalize(self.item_encoder(i), dim=-1)
        return (u * i).sum(-1)`}</Code>
      </Section>

      <Section id="training" title="8. Training Strategy">
        <ul className="list-disc space-y-1 pl-5">
          <li>Sampled softmax over 4k in-batch negatives + hard negatives from ANN.</li>
          <li>Cosine LR schedule with 3% warmup, AdamW, bf16 on 8×A100.</li>
          <li>Ranker fine-tuned with pairwise logistic loss weighted by conversion value.</li>
          <li>Deterministic seeds, per-epoch offline eval on held-out sessions.</li>
        </ul>
      </Section>

      <Section id="system" title="9. System Architecture">
        <p>End-to-end topology:</p>
        <pre className="rounded-lg bg-muted p-3 text-xs">{`Kafka events ─▶ Feature Store (Feast) ─▶ Training (Ray/PyTorch) ─▶ Model Registry
                          │                                               │
                          ▼                                               ▼
                 Online features ◀────────── Triton Ranker ◀──── FAISS Retrieval
                          │                          │
                          └────────────▶ API Gateway ▶ Storefront`}</pre>
        <Figure src="https://images.unsplash.com/photo-1518770660439-4636190af475?w=1400&q=80" caption="Figure 2 — Production topology: streaming events, feature store, retrieval + ranker, and observability plane." />
      </Section>

      <Section id="deployment" title="10. Deployment Pipeline">
        <p>
          Models are packaged as TorchScript, benchmarked against a golden traffic sample, then
          promoted through canary (1%) → shadow (25% mirrored) → full rollout. Every promotion
          gate is a pull-request check.
        </p>
      </Section>

      <Section id="monitoring" title="11. Monitoring & Maintenance">
        <ul className="list-disc space-y-1 pl-5">
          <li>Prometheus for latency, QPS, memory, GPU utilisation.</li>
          <li>Feature-drift PSI on top 40 features; alerts on PSI &gt; 0.2.</li>
          <li>Weekly counterfactual holdout comparing model vs previous champion.</li>
        </ul>
      </Section>

      <Section id="performance" title="12. Performance Evaluation">
        <table className="w-full border-collapse text-sm">
          <thead><tr className="border-b"><th className="p-2 text-left">Metric</th><th className="p-2 text-left">Baseline</th><th className="p-2 text-left">DL model</th><th className="p-2 text-left">Δ</th></tr></thead>
          <tbody>
            <tr className="border-b"><td className="p-2">CTR</td><td className="p-2">3.1%</td><td className="p-2">3.9%</td><td className="p-2">+26%</td></tr>
            <tr className="border-b"><td className="p-2">RPV</td><td className="p-2">$1.42</td><td className="p-2">$1.61</td><td className="p-2">+13%</td></tr>
            <tr className="border-b"><td className="p-2">p99 latency</td><td className="p-2">140ms</td><td className="p-2">78ms</td><td className="p-2">-44%</td></tr>
            <tr><td className="p-2">Long-tail coverage</td><td className="p-2">16%</td><td className="p-2">34%</td><td className="p-2">+112%</td></tr>
          </tbody>
        </table>
      </Section>

      <Section id="business" title="13. Business Outcomes">
        <Callout tone="success" icon={<Sparkles className="h-5 w-5" />} title="Impact">
          <p>Annualised revenue uplift of <strong>$34M</strong>, a 22-week payback on the platform investment, and merchandising time-to-launch reduced from 5 days to 40 minutes.</p>
        </Callout>
      </Section>

      <Section id="lessons" title="14. Lessons Learned">
        <ul className="list-disc space-y-1 pl-5">
          <li>Data quality dominated model choice — three of the biggest wins came from labels, not layers.</li>
          <li>Serving costs were dictated by the ranker, not the retriever — distillation was worth the effort.</li>
          <li>Shadow deploys caught two silent regressions that offline metrics missed entirely.</li>
        </ul>
      </Section>

      <Section id="future" title="15. Future Enhancements">
        <ul className="list-disc space-y-1 pl-5">
          <li>Multimodal item towers using CLIP image embeddings and product-video summaries.</li>
          <li>Session-level transformer ranker with RL fine-tuning against long-term reward.</li>
          <li>On-device pre-fetch of top-N candidates to reduce cold-start latency further.</li>
        </ul>
      </Section>

      <Section id="review" title="Real-world Review">
        <h3 className="font-semibold">Executive summary</h3>
        <p>DL delivered a step-change in ranking quality and reduced serving latency simultaneously — a rare combination that unlocked broader roadmap ambition.</p>
        <h3 className="mt-3 font-semibold">Engineering takeaways</h3>
        <ul className="list-disc space-y-1 pl-5">
          <li>Feature store discipline pays for itself the first time you retrain.</li>
          <li>Retrieval + ranker separation kept latency predictable at scale.</li>
          <li>Canary + shadow deploys were the highest-ROI SRE investment.</li>
        </ul>
        <h3 className="mt-3 font-semibold">Discussion questions</h3>
        <ul className="list-disc space-y-1 pl-5">
          <li>How would you re-scope this project for a team of two?</li>
          <li>Which guardrails would you add to protect long-tail exposure?</li>
          <li>Where would multimodal signals move the needle first?</li>
        </ul>
        <h3 className="mt-3 font-semibold">Reflection activities</h3>
        <ul className="list-disc space-y-1 pl-5">
          <li>Draft an equivalent architecture diagram for a marketplace with only 20k items.</li>
          <li>Sketch a rollback playbook for a mis-behaving canary at 2% traffic.</li>
        </ul>
        <h3 className="mt-3 font-semibold">Industry insights</h3>
        <p>Two-tower + cross-attention ranker is the current default at most large recommender systems (Meta, Pinterest, Alibaba, Netflix). The differentiator is feature engineering and evaluation discipline, not architecture novelty.</p>
      </Section>

      <Section id="summary" title="Summary & Key Takeaways">
        <ul className="list-disc space-y-1 pl-5">
          <li>Frame the business problem before choosing the model.</li>
          <li>Feature stores, canaries, and drift monitoring make DL projects survivable.</li>
          <li>Measurable outcomes — CTR, RPV, latency — are the only language leadership rewards.</li>
        </ul>
      </Section>

      <Section id="faqs" title="FAQ">
        <FAQItem q="Why two-tower and not a single ranker?">Retrieval + ranker separates a fast approximate step from an expensive precise step, letting you scale independently.</FAQItem>
        <FAQItem q="How was cold-start solved?">Item towers depend only on catalogue features, so a new SKU is rankable the moment it lands in Feast.</FAQItem>
        <FAQItem q="Is TensorFlow a viable substitute?">Yes — the architecture is framework-agnostic. PyTorch was chosen for team familiarity and Triton compatibility.</FAQItem>
      </Section>

      <Section id="glossary" title="Glossary">
        <ul className="list-disc space-y-1 pl-5">
          <li><strong>ANN</strong> — Approximate Nearest Neighbour search (e.g. FAISS, ScaNN).</li>
          <li><strong>PSI</strong> — Population Stability Index for feature drift.</li>
          <li><strong>RPV</strong> — Revenue Per Visit.</li>
          <li><strong>Triton</strong> — NVIDIA inference server supporting multi-framework model serving.</li>
        </ul>
      </Section>

      <Section id="references" title="References"><References /></Section>

      <Section id="disclaimer" title="Disclaimer">
        <p className="text-sm text-muted-foreground">
          This resource is intended for educational purposes only. Information is compiled from
          official documentation, academic publications, research papers, industry standards, and
          trusted educational resources. The company, metrics, and figures in this case study are
          illustrative. Deep learning technologies, frameworks, APIs, and best practices evolve
          continuously — consult the latest official documentation for authoritative guidance. All
          trademarks, logos, product names, and intellectual property belong to their respective
          owners.
        </p>
      </Section>
    </ReaderShell>
  );
}
