// Course → Resources catalog. Every course in Explore has a matching entry
// here so its dedicated Resources page can render the full set of documents
// and articles (no videos, no external links).

export type ResourceKind =
  | "Beginner Guide"
  | "Complete Tutorial"
  | "Step-by-Step Learning Guide"
  | "PDF Notes"
  | "Quick Revision Notes"
  | "Cheat Sheet"
  | "Interview Questions"
  | "Practice Questions"
  | "Answer Key"
  | "Sample Exercises"
  | "Project Guide"
  | "Project Case Study"
  | "Real-world Case Study"
  | "Best Practices"
  | "Common Mistakes"
  | "Frequently Asked Questions"
  | "Learning Roadmap"
  | "Tips & Tricks"
  | "Advanced Concepts"
  | "Glossary"
  | "Reference Guide";

export const RESOURCE_KINDS: ResourceKind[] = [
  "Beginner Guide",
  "Complete Tutorial",
  "Step-by-Step Learning Guide",
  "PDF Notes",
  "Quick Revision Notes",
  "Cheat Sheet",
  "Interview Questions",
  "Practice Questions",
  "Answer Key",
  "Sample Exercises",
  "Project Guide",
  "Project Case Study",
  "Real-world Case Study",
  "Best Practices",
  "Common Mistakes",
  "Frequently Asked Questions",
  "Learning Roadmap",
  "Tips & Tricks",
  "Advanced Concepts",
  "Glossary",
  "Reference Guide",
];

export type CourseCatalogEntry = {
  slug: string;
  title: string;
  category: string; // Group label e.g. "AI & Data"
  tagline: string;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  tags: string[];
  gradient: string; // Tailwind gradient class stem for cover
};

export const COURSE_CATALOG: CourseCatalogEntry[] = [
  // AI & Data
  { slug: "artificial-intelligence", title: "Artificial Intelligence", category: "AI & Data", tagline: "Foundations of AI — search, reasoning, learning, and modern neural approaches.", difficulty: "Intermediate", tags: ["AI", "Neural Nets", "Search"], gradient: "from-violet-500 to-fuchsia-500" },
  { slug: "machine-learning", title: "Machine Learning", category: "AI & Data", tagline: "Regression, classification, ensembles, and evaluation with scikit-learn.", difficulty: "Intermediate", tags: ["ML", "Python", "scikit-learn"], gradient: "from-violet-500 to-purple-500" },
  { slug: "deep-learning", title: "Deep Learning", category: "AI & Data", tagline: "Neural networks, CNNs, RNNs, transformers, and modern training regimes.", difficulty: "Advanced", tags: ["DL", "PyTorch", "Transformers"], gradient: "from-fuchsia-500 to-pink-500" },
  { slug: "generative-ai", title: "Generative AI", category: "AI & Data", tagline: "LLMs, diffusion, RAG, and shipping GenAI features to production.", difficulty: "Advanced", tags: ["GenAI", "LLM", "RAG"], gradient: "from-purple-500 to-violet-500" },
  { slug: "prompt-engineering", title: "Prompt Engineering", category: "AI & Data", tagline: "Reliable prompts, chains, evaluations, and prompt-driven pipelines.", difficulty: "Intermediate", tags: ["Prompts", "LLM", "Eval"], gradient: "from-violet-500 to-indigo-500" },
  { slug: "ai-agents", title: "AI Agents", category: "AI & Data", tagline: "Tool-use, memory, planning, and multi-step autonomous workflows.", difficulty: "Advanced", tags: ["Agents", "LLM", "Tools"], gradient: "from-fuchsia-500 to-violet-500" },

  // Programming
  { slug: "python", title: "Python", category: "Programming", tagline: "Syntax to advanced Python — the fastest path to fluent, idiomatic code.", difficulty: "Beginner", tags: ["Python", "OOP", "Std lib"], gradient: "from-sky-500 to-cyan-500" },
  { slug: "java", title: "Java", category: "Programming", tagline: "OOP, collections, streams, and the JVM you'll use at work.", difficulty: "Beginner", tags: ["Java", "OOP", "JVM"], gradient: "from-red-500 to-orange-500" },
  { slug: "c-programming", title: "C Programming", category: "Programming", tagline: "Memory model, pointers, and systems-level programming.", difficulty: "Beginner", tags: ["C", "Pointers", "Systems"], gradient: "from-blue-500 to-sky-500" },
  { slug: "cpp", title: "C++", category: "Programming", tagline: "Modern C++: RAII, templates, STL, and performance-critical patterns.", difficulty: "Intermediate", tags: ["C++", "STL", "Templates"], gradient: "from-blue-600 to-indigo-500" },
  { slug: "javascript", title: "JavaScript", category: "Programming", tagline: "Language deep-dive: closures, prototypes, async, and modules.", difficulty: "Beginner", tags: ["JS", "ES2020+", "Async"], gradient: "from-yellow-500 to-amber-500" },
  { slug: "typescript", title: "TypeScript", category: "Programming", tagline: "Types, generics, narrowing, and shipping robust JS at scale.", difficulty: "Intermediate", tags: ["TS", "Types", "Generics"], gradient: "from-sky-500 to-blue-500" },
  { slug: "go", title: "Go", category: "Programming", tagline: "Goroutines, channels, tooling — writing simple, fast backends in Go.", difficulty: "Intermediate", tags: ["Go", "Concurrency"], gradient: "from-cyan-500 to-sky-500" },
  { slug: "rust", title: "Rust", category: "Programming", tagline: "Ownership, borrowing, traits — safe systems programming.", difficulty: "Advanced", tags: ["Rust", "Systems", "Safety"], gradient: "from-orange-500 to-red-500" },

  // Web
  { slug: "html5", title: "HTML5", category: "Web Development", tagline: "Semantic markup, accessibility, and modern document structure.", difficulty: "Beginner", tags: ["HTML", "A11y"], gradient: "from-orange-500 to-amber-500" },
  { slug: "css3", title: "CSS3", category: "Web Development", tagline: "Layout, responsiveness, animations, and design-system fundamentals.", difficulty: "Beginner", tags: ["CSS", "Flexbox", "Grid"], gradient: "from-blue-500 to-indigo-500" },
  { slug: "tailwind-css", title: "Tailwind CSS", category: "Web Development", tagline: "Utility-first styling, tokens, and building a scalable design system.", difficulty: "Beginner", tags: ["Tailwind", "Design"], gradient: "from-cyan-500 to-sky-500" },
  { slug: "react", title: "React.js", category: "Web Development", tagline: "Hooks, state, routing, patterns, and production React apps.", difficulty: "Intermediate", tags: ["React", "Hooks"], gradient: "from-cyan-500 to-blue-500" },
  { slug: "nextjs", title: "Next.js", category: "Web Development", tagline: "App router, server components, streaming, and shipping full-stack apps.", difficulty: "Intermediate", tags: ["Next.js", "SSR"], gradient: "from-slate-500 to-zinc-500" },
  { slug: "angular", title: "Angular", category: "Web Development", tagline: "Components, DI, RxJS, and building large-scale enterprise SPAs.", difficulty: "Intermediate", tags: ["Angular", "RxJS"], gradient: "from-red-500 to-rose-500" },
  { slug: "vue", title: "Vue.js", category: "Web Development", tagline: "Composition API, reactivity, and building focused SPAs.", difficulty: "Intermediate", tags: ["Vue", "Composition"], gradient: "from-emerald-500 to-teal-500" },
  { slug: "nodejs", title: "Node.js", category: "Web Development", tagline: "Event loop, streams, and building scalable backend services.", difficulty: "Intermediate", tags: ["Node", "Backend"], gradient: "from-lime-500 to-green-500" },
  { slug: "expressjs", title: "Express.js", category: "Web Development", tagline: "Routing, middleware, and REST APIs with Node + Express.", difficulty: "Intermediate", tags: ["Express", "REST"], gradient: "from-neutral-500 to-slate-500" },
  { slug: "mern-stack", title: "MERN Stack", category: "Web Development", tagline: "Mongo, Express, React, Node — end-to-end full-stack development.", difficulty: "Intermediate", tags: ["MERN", "Fullstack"], gradient: "from-emerald-500 to-teal-500" },

  // Mobile
  { slug: "flutter", title: "Flutter", category: "Mobile", tagline: "Widgets, state, and shipping beautiful cross-platform apps.", difficulty: "Intermediate", tags: ["Flutter", "Dart"], gradient: "from-teal-500 to-cyan-500" },
  { slug: "android", title: "Android Development", category: "Mobile", tagline: "Activities, Jetpack, and building production Android apps.", difficulty: "Intermediate", tags: ["Android", "Jetpack"], gradient: "from-green-500 to-emerald-500" },
  { slug: "kotlin", title: "Kotlin", category: "Mobile", tagline: "Idiomatic Kotlin for Android — coroutines, sealed classes, and DSLs.", difficulty: "Intermediate", tags: ["Kotlin", "Coroutines"], gradient: "from-violet-500 to-purple-500" },
  { slug: "swift-ios", title: "Swift (iOS)", category: "Mobile", tagline: "SwiftUI, concurrency, and shipping polished iOS apps.", difficulty: "Intermediate", tags: ["Swift", "SwiftUI"], gradient: "from-orange-500 to-red-500" },

  // Databases
  { slug: "sql", title: "SQL", category: "Databases", tagline: "Queries, joins, indexes, and thinking relationally.", difficulty: "Beginner", tags: ["SQL", "RDBMS"], gradient: "from-indigo-500 to-blue-500" },
  { slug: "mysql", title: "MySQL", category: "Databases", tagline: "Schema design, tuning, and production MySQL patterns.", difficulty: "Intermediate", tags: ["MySQL", "Tuning"], gradient: "from-blue-500 to-cyan-500" },
  { slug: "postgresql", title: "PostgreSQL", category: "Databases", tagline: "Advanced Postgres: JSONB, CTEs, indexes, and performance.", difficulty: "Intermediate", tags: ["Postgres", "JSONB"], gradient: "from-sky-500 to-blue-500" },
  { slug: "mongodb", title: "MongoDB", category: "Databases", tagline: "Schema design, aggregation, and production-ready MongoDB.", difficulty: "Intermediate", tags: ["Mongo", "Aggregation"], gradient: "from-emerald-500 to-green-500" },

  // Data & Analytics
  { slug: "data-science", title: "Data Science", category: "Data & Analytics", tagline: "Analytics, ML, visualization, and storytelling with data.", difficulty: "Intermediate", tags: ["Data", "ML", "Viz"], gradient: "from-pink-500 to-rose-500" },
  { slug: "data-analytics", title: "Data Analytics", category: "Data & Analytics", tagline: "SQL, Excel, Python, and BI tools for data-driven decisions.", difficulty: "Beginner", tags: ["Analytics", "SQL", "BI"], gradient: "from-pink-500 to-fuchsia-500" },
  { slug: "numpy", title: "NumPy", category: "Data & Analytics", tagline: "Arrays, broadcasting, and numerical computing in Python.", difficulty: "Beginner", tags: ["NumPy", "Python"], gradient: "from-rose-500 to-pink-500" },
  { slug: "pandas", title: "Pandas", category: "Data & Analytics", tagline: "DataFrames, groupby, joins, and real-world data wrangling.", difficulty: "Beginner", tags: ["Pandas", "Python"], gradient: "from-pink-500 to-rose-500" },
  { slug: "power-bi", title: "Power BI", category: "Data & Analytics", tagline: "Modeling, DAX, and building executive-ready dashboards.", difficulty: "Beginner", tags: ["Power BI", "DAX"], gradient: "from-yellow-500 to-amber-500" },
  { slug: "tableau", title: "Tableau", category: "Data & Analytics", tagline: "Visual analytics, calculated fields, and interactive dashboards.", difficulty: "Beginner", tags: ["Tableau", "Viz"], gradient: "from-blue-500 to-indigo-500" },

  // Cloud & DevOps
  { slug: "aws", title: "AWS", category: "Cloud & DevOps", tagline: "Core AWS services, architecture principles, and exam-ready practice.", difficulty: "Beginner", tags: ["AWS", "Cloud"], gradient: "from-orange-500 to-amber-500" },
  { slug: "azure", title: "Microsoft Azure", category: "Cloud & DevOps", tagline: "Azure fundamentals — compute, storage, networking, and identity.", difficulty: "Beginner", tags: ["Azure", "Cloud"], gradient: "from-sky-500 to-blue-500" },
  { slug: "gcp", title: "Google Cloud Platform", category: "Cloud & DevOps", tagline: "GCP core services and cloud-native patterns.", difficulty: "Beginner", tags: ["GCP", "Cloud"], gradient: "from-blue-500 to-cyan-500" },
  { slug: "docker", title: "Docker", category: "Cloud & DevOps", tagline: "Images, containers, networks, and shipping reproducible builds.", difficulty: "Intermediate", tags: ["Docker", "Containers"], gradient: "from-cyan-500 to-blue-500" },
  { slug: "kubernetes", title: "Kubernetes", category: "Cloud & DevOps", tagline: "Pods, deployments, services, and orchestrating production workloads.", difficulty: "Advanced", tags: ["K8s", "Orchestration"], gradient: "from-sky-500 to-blue-500" },
  { slug: "devops", title: "DevOps", category: "Cloud & DevOps", tagline: "CI/CD, IaC, observability, and shipping software faster and safer.", difficulty: "Intermediate", tags: ["DevOps", "CI/CD"], gradient: "from-teal-500 to-emerald-500" },

  // Security
  { slug: "cyber-security", title: "Cyber Security", category: "Security", tagline: "Threats, defenses, and building a security mindset.", difficulty: "Beginner", tags: ["Security", "Defense"], gradient: "from-red-500 to-rose-500" },
  { slug: "ethical-hacking", title: "Ethical Hacking", category: "Security", tagline: "Recon, exploitation, and reporting — offensive security fundamentals.", difficulty: "Advanced", tags: ["Hacking", "Pentest"], gradient: "from-orange-500 to-red-500" },
  { slug: "network-security", title: "Network Security", category: "Security", tagline: "Protocols, firewalls, and securing network infrastructure.", difficulty: "Intermediate", tags: ["Network", "Security"], gradient: "from-slate-500 to-zinc-500" },
  { slug: "penetration-testing", title: "Penetration Testing", category: "Security", tagline: "Methodology, tooling, and hands-on pentest engagements.", difficulty: "Advanced", tags: ["Pentest", "Offensive"], gradient: "from-red-500 to-orange-500" },

  // Design
  { slug: "ui-design", title: "UI Design", category: "Design", tagline: "Visual design principles, hierarchy, and building beautiful UIs.", difficulty: "Beginner", tags: ["UI", "Design"], gradient: "from-fuchsia-500 to-pink-500" },
  { slug: "ux-design", title: "UX Design", category: "Design", tagline: "Research, journeys, and designing experiences users love.", difficulty: "Beginner", tags: ["UX", "Research"], gradient: "from-pink-500 to-rose-500" },
  { slug: "figma", title: "Figma", category: "Design", tagline: "Auto-layout, components, and building production design systems.", difficulty: "Beginner", tags: ["Figma", "Design Systems"], gradient: "from-purple-500 to-fuchsia-500" },

  // CS Core
  { slug: "dsa", title: "Data Structures & Algorithms", category: "CS Core", tagline: "Patterns, complexity, and 200+ interview-ready problems.", difficulty: "Intermediate", tags: ["DSA", "Interview"], gradient: "from-blue-500 to-indigo-500" },
  { slug: "operating-systems", title: "Operating Systems", category: "CS Core", tagline: "Processes, memory, filesystems, and how modern OSes work.", difficulty: "Intermediate", tags: ["OS", "Systems"], gradient: "from-indigo-500 to-violet-500" },
  { slug: "computer-networks", title: "Computer Networks", category: "CS Core", tagline: "TCP/IP, routing, and the internet from packets up.", difficulty: "Intermediate", tags: ["Networks", "TCP/IP"], gradient: "from-blue-500 to-sky-500" },
  { slug: "dbms", title: "DBMS", category: "CS Core", tagline: "Relational model, normalization, transactions, and indexing.", difficulty: "Intermediate", tags: ["DBMS", "SQL"], gradient: "from-indigo-500 to-blue-500" },
  { slug: "system-design", title: "System Design", category: "CS Core", tagline: "Scalable architectures, trade-offs, and interview case studies.", difficulty: "Advanced", tags: ["System Design", "Scale"], gradient: "from-indigo-500 to-violet-500" },
];

export function getCourseBySlug(slug: string) {
  return COURSE_CATALOG.find((c) => c.slug === slug) ?? null;
}

export function getRelatedCourses(slug: string, limit = 4) {
  const cur = getCourseBySlug(slug);
  if (!cur) return [];
  return COURSE_CATALOG.filter((c) => c.slug !== slug && c.category === cur.category).slice(0, limit);
}

// ---------------------------------------------------------------------------
// Topic-relevant imagery. Curated Unsplash photo IDs mapped per category with
// slug-level overrides for major courses so covers stay consistent across the
// library while remaining specific to each topic.
// ---------------------------------------------------------------------------

const CATEGORY_IMAGE: Record<string, string> = {
  "AI & Data": "photo-1620712943543-bcc4688e7485",
  "Programming": "photo-1461749280684-dccba630e2f6",
  "Web Development": "photo-1547658719-da2b51169166",
  "Mobile": "photo-1512941937669-90a1b58e7e9c",
  "Databases": "photo-1544383835-bda2bc66a55d",
  "Data & Analytics": "photo-1551288049-bebda4e38f71",
  "Cloud & DevOps": "photo-1451187580459-43490279c0fa",
  "Security": "photo-1550751827-4bd374c3f58b",
  "Design": "photo-1561070791-2526d30994b8",
  "CS Core": "photo-1518770660439-4636190af475",
};

const SLUG_IMAGE: Record<string, string> = {
  "artificial-intelligence": "photo-1620712943543-bcc4688e7485",
  "machine-learning": "photo-1555949963-aa79dcee981c",
  "deep-learning": "photo-1677442136019-21780ecad995",
  "generative-ai": "photo-1673187456554-11de9df2f83e",
  "prompt-engineering": "photo-1526378787940-576a539ba69d",
  "ai-agents": "photo-1535378917042-10a22c95931a",
  "python": "photo-1526379095098-d400fd0bf935",
  "java": "photo-1517694712202-14dd9538aa97",
  "c-programming": "photo-1580927752452-89d86da3fa0a",
  "cpp": "photo-1629654297299-c8506221ca97",
  "javascript": "photo-1579468118864-1b9ea3c0db4a",
  "typescript": "photo-1587620962725-abab7fe55159",
  "react": "photo-1633356122544-f134324a6cee",
  "nextjs": "photo-1555066931-4365d14bab8c",
  "nodejs": "photo-1627398242454-45a1465c2479",
  "html5": "photo-1621839673705-6617adf9e890",
  "css3": "photo-1507721999472-8ed4421c4af2",
  "flutter": "photo-1607252650355-f7fd0460ccdb",
  "android": "photo-1607252650355-f7fd0460ccdb",
  "swift-ios": "photo-1512941937669-90a1b58e7e9c",
  "sql": "photo-1544383835-bda2bc66a55d",
  "mysql": "photo-1544383835-bda2bc66a55d",
  "postgresql": "photo-1633412802994-5c058f151b66",
  "mongodb": "photo-1633412802994-5c058f151b66",
  "data-science": "photo-1460925895917-afdab827c52f",
  "data-analytics": "photo-1551288049-bebda4e38f71",
  "aws": "photo-1451187580459-43490279c0fa",
  "azure": "photo-1451187580459-43490279c0fa",
  "gcp": "photo-1451187580459-43490279c0fa",
  "docker": "photo-1605745341112-85968b19335b",
  "kubernetes": "photo-1667372393119-3d4c48d07fc9",
  "devops": "photo-1607705703571-c5a8695f18f6",
  "cyber-security": "photo-1563986768609-322da13575f3",
  "ethical-hacking": "photo-1526628953301-3e589a6a8b74",
  "network-security": "photo-1544197150-b99a580bb7a8",
  "penetration-testing": "photo-1550751827-4bd374c3f58b",
  "ui-design": "photo-1561070791-2526d30994b8",
  "ux-design": "photo-1586717791821-3f44a563fa4c",
  "figma": "photo-1609921212029-bb5a28e60960",
  "dsa": "photo-1518770660439-4636190af475",
  "operating-systems": "photo-1518770660439-4636190af475",
  "computer-networks": "photo-1544197150-b99a580bb7a8",
  "system-design": "photo-1518770660439-4636190af475",
};

export function getCourseImage(course: { slug: string; category: string }): string {
  const id = SLUG_IMAGE[course.slug] ?? CATEGORY_IMAGE[course.category] ?? "photo-1518770660439-4636190af475";
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=80`;
}

// ---------------------------------------------------------------------------
// Deterministic resource metadata generation. Given a course + resource kind,
// produce consistent title, summary, reading time, pages, tags. Keeps the
// library scalable to thousands of resources without hand-writing each one.
// ---------------------------------------------------------------------------

function hash(str: string) {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return Math.abs(h);
}

const KIND_META: Record<
  ResourceKind,
  { blurb: (t: string) => string; pages: [number, number]; readMin: [number, number]; difficulty: "Beginner" | "Intermediate" | "Advanced" | "All" }
> = {
  "Beginner Guide": { blurb: (t) => `A friendly first walk through ${t}: core concepts, mental models, and your first hands-on exercises.`, pages: [14, 28], readMin: [10, 18], difficulty: "Beginner" },
  "Complete Tutorial": { blurb: (t) => `An end-to-end tutorial covering every essential topic in ${t}, from setup to shipping a real project.`, pages: [60, 120], readMin: [40, 75], difficulty: "All" },
  "Step-by-Step Learning Guide": { blurb: (t) => `A structured, week-by-week study plan for ${t} with milestones, exercises, and self-checks.`, pages: [22, 44], readMin: [18, 28], difficulty: "All" },
  "PDF Notes": { blurb: (t) => `Complete chapter-wise notes for ${t}, formatted for revision and offline study.`, pages: [80, 160], readMin: [50, 90], difficulty: "All" },
  "Quick Revision Notes": { blurb: (t) => `Condensed one-pager revision notes for ${t} — perfect for exam eve or interview prep.`, pages: [4, 10], readMin: [6, 12], difficulty: "All" },
  "Cheat Sheet": { blurb: (t) => `The essential ${t} syntax, patterns, and gotchas on a single, printable reference sheet.`, pages: [2, 4], readMin: [3, 6], difficulty: "All" },
  "Interview Questions": { blurb: (t) => `Curated interview questions for ${t} with layered hints and detailed model answers.`, pages: [30, 60], readMin: [25, 45], difficulty: "Intermediate" },
  "Practice Questions": { blurb: (t) => `A themed practice set for ${t} with progressive difficulty and worked solutions.`, pages: [20, 40], readMin: [20, 35], difficulty: "All" },
  "Answer Key": { blurb: (t) => `Fully worked answers and rubric-based explanations for the ${t} practice set.`, pages: [24, 48], readMin: [20, 35], difficulty: "All" },
  "Sample Exercises": { blurb: (t) => `Warm-up and applied exercises for ${t}, grouped by concept for spaced practice.`, pages: [18, 34], readMin: [15, 25], difficulty: "Beginner" },
  "Project Guide": { blurb: (t) => `A hands-on project brief for ${t}: requirements, milestones, and a review checklist.`, pages: [16, 30], readMin: [15, 25], difficulty: "Intermediate" },
  "Project Case Study": { blurb: (t) => `A production project built with ${t} — background, architecture, decisions, and outcomes.`, pages: [24, 48], readMin: [20, 30], difficulty: "Intermediate" },
  "Real-world Case Study": { blurb: (t) => `How a real team applied ${t} to a business problem — problem, solution, and lessons learned.`, pages: [18, 36], readMin: [15, 25], difficulty: "Intermediate" },
  "Best Practices": { blurb: (t) => `The battle-tested patterns, conventions, and defaults that make ${t} projects maintainable.`, pages: [12, 24], readMin: [12, 20], difficulty: "Intermediate" },
  "Common Mistakes": { blurb: (t) => `The most frequent ${t} mistakes, why they happen, and how to fix them for good.`, pages: [10, 20], readMin: [10, 16], difficulty: "All" },
  "Frequently Asked Questions": { blurb: (t) => `The most-asked questions about ${t}, answered clearly with examples.`, pages: [8, 16], readMin: [8, 14], difficulty: "All" },
  "Learning Roadmap": { blurb: (t) => `A visual roadmap for ${t} — what to learn, in what order, and how to know you're ready.`, pages: [6, 12], readMin: [6, 10], difficulty: "All" },
  "Tips & Tricks": { blurb: (t) => `Practical productivity tips, keyboard flows, and shortcuts for working faster with ${t}.`, pages: [8, 16], readMin: [8, 12], difficulty: "All" },
  "Advanced Concepts": { blurb: (t) => `A deep dive into the advanced corners of ${t}: internals, edge cases, and expert patterns.`, pages: [30, 60], readMin: [25, 40], difficulty: "Advanced" },
  "Glossary": { blurb: (t) => `A comprehensive glossary of ${t} terms, acronyms, and concepts with plain-language definitions.`, pages: [10, 22], readMin: [8, 15], difficulty: "All" },
  "Reference Guide": { blurb: (t) => `A dense, lookup-optimized reference for ${t} APIs, syntax, and configuration.`, pages: [40, 90], readMin: [30, 60], difficulty: "All" },
};

const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October"];

export type CourseResource = {
  id: string;
  courseSlug: string;
  kind: ResourceKind;
  title: string;
  summary: string;
  pages: number;
  readingMinutes: number;
  difficulty: "Beginner" | "Intermediate" | "Advanced" | "All";
  lastUpdated: string;
  tags: string[];
  gradient: string;
};

function pick<T>(arr: T[], seed: number) {
  return arr[seed % arr.length];
}

function inRange([lo, hi]: [number, number], seed: number) {
  return lo + (seed % (hi - lo + 1));
}

export function buildCourseResources(course: CourseCatalogEntry): CourseResource[] {
  return RESOURCE_KINDS.map((kind) => {
    const meta = KIND_META[kind];
    const seed = hash(`${course.slug}::${kind}`);
    const pages = inRange(meta.pages, seed);
    const readingMinutes = inRange(meta.readMin, seed >> 3);
    const month = pick(MONTHS, seed >> 5);
    const year = 2026;
    return {
      id: `${course.slug}--${kind.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
      courseSlug: course.slug,
      kind,
      title: `${course.title} — ${kind}`,
      summary: meta.blurb(course.title),
      pages,
      readingMinutes,
      difficulty: meta.difficulty === "All" ? "Beginner" : meta.difficulty,
      lastUpdated: `${month} ${year}`,
      tags: [course.category, ...course.tags.slice(0, 2), kind],
      gradient: course.gradient,
    };
  });
}

// Reader routes physically implemented under src/routes/_marketing.resources.read.*
// Keyed by resource id (`<courseSlug>--<kind-slug>`). Add entries here as new
// dedicated reader pages are built.
const READER_ROUTES: Record<string, string> = {
  "artificial-intelligence--beginner-guide": "/resources/read/ai-beginner-guide",
  "artificial-intelligence--complete-tutorial": "/resources/read/ai-complete-tutorial",
  "artificial-intelligence--step-by-step-learning-guide": "/resources/read/ai-step-by-step-learning-guide",
  "artificial-intelligence--pdf-notes": "/resources/read/ai-pdf-notes",
  "artificial-intelligence--quick-revision-notes": "/resources/read/ai-quick-revision-notes",
  "artificial-intelligence--cheat-sheet": "/resources/read/ai-cheat-sheet",
  "artificial-intelligence--interview-questions": "/resources/read/ai-interview-questions",
  "artificial-intelligence--practice-questions": "/resources/read/ai-practice-questions",
  "artificial-intelligence--answer-key": "/resources/read/ai-answer-key",
  "artificial-intelligence--sample-exercises": "/resources/read/ai-sample-exercises",
  "artificial-intelligence--project-guide": "/resources/read/ai-project-guide",
  "artificial-intelligence--project-case-study": "/resources/read/ai-project-case-study",
  "artificial-intelligence--real-world-case-study": "/resources/read/ai-real-world-case-study",
  "artificial-intelligence--best-practices": "/resources/read/ai-best-practices",
  "artificial-intelligence--common-mistakes": "/resources/read/ai-common-mistakes",
  "artificial-intelligence--frequently-asked-questions": "/resources/read/ai-frequently-asked-questions",
  "artificial-intelligence--learning-roadmap": "/resources/read/ai-learning-roadmap",
  "artificial-intelligence--tips-tricks": "/resources/read/ai-tips-tricks",
  "artificial-intelligence--advanced-concepts": "/resources/read/ai-advanced-concepts",
  "artificial-intelligence--glossary": "/resources/read/ai-glossary",
  "artificial-intelligence--reference-guide": "/resources/read/ai-reference-guide",
  "machine-learning--beginner-guide": "/resources/read/ml-beginner-guide",
  "machine-learning--complete-tutorial": "/resources/read/ml-complete-tutorial",
  "machine-learning--step-by-step-learning-guide": "/resources/read/ml-step-by-step-learning-guide",
  "machine-learning--pdf-notes": "/resources/read/ml-pdf-notes",
  "machine-learning--quick-revision-notes": "/resources/read/ml-quick-revision-notes",
  "machine-learning--cheat-sheet": "/resources/read/ml-cheat-sheet",
  "machine-learning--interview-questions": "/resources/read/ml-interview-questions",
  "machine-learning--practice-questions": "/resources/read/ml-practice-questions",
  "machine-learning--answer-key": "/resources/read/ml-answer-key",
  "machine-learning--sample-exercises": "/resources/read/ml-sample-exercises",
  "machine-learning--project-guide": "/resources/read/ml-project-guide",
  "machine-learning--project-case-study": "/resources/read/ml-project-case-study",
  "machine-learning--real-world-case-study": "/resources/read/ml-real-world-case-study",
  "machine-learning--best-practices": "/resources/read/ml-best-practices",
  "machine-learning--common-mistakes": "/resources/read/ml-common-mistakes",
  "machine-learning--frequently-asked-questions": "/resources/read/ml-frequently-asked-questions",
  "machine-learning--learning-roadmap": "/resources/read/ml-learning-roadmap",
  "machine-learning--tips-tricks": "/resources/read/ml-tips-tricks",
  "machine-learning--advanced-concepts": "/resources/read/ml-advanced-concepts",
  "machine-learning--glossary": "/resources/read/ml-glossary",
  "machine-learning--reference-guide": "/resources/read/ml-reference-guide",
  "deep-learning--advanced-concepts": "/resources/read/dl-advanced-concepts",
  "deep-learning--glossary": "/resources/read/dl-glossary",
  "deep-learning--reference-guide": "/resources/read/dl-reference-guide",
  "deep-learning--frequently-asked-questions": "/resources/read/dl-frequently-asked-questions",
  "deep-learning--learning-roadmap": "/resources/read/dl-learning-roadmap",
  "deep-learning--tips-tricks": "/resources/read/dl-tips-tricks",
  "deep-learning--real-world-case-study": "/resources/read/dl-real-world-case-study",
  "deep-learning--best-practices": "/resources/read/dl-best-practices",
  "deep-learning--common-mistakes": "/resources/read/dl-common-mistakes",
  "deep-learning--interview-questions": "/resources/read/dl-interview-questions",
  "deep-learning--practice-questions": "/resources/read/dl-practice-questions",
  "deep-learning--answer-key": "/resources/read/dl-answer-key",
  "deep-learning--sample-exercises": "/resources/read/dl-sample-exercises",
  "deep-learning--project-guide": "/resources/read/dl-project-guide",
  "deep-learning--project-case-study": "/resources/read/dl-project-case-study",
  "deep-learning--beginner-guide": "/resources/read/dl-beginner-guide",
  "deep-learning--complete-tutorial": "/resources/read/dl-complete-tutorial",
  "deep-learning--step-by-step-learning-guide": "/resources/read/dl-step-by-step-learning-guide",
  "deep-learning--pdf-notes": "/resources/read/dl-pdf-notes",
  "deep-learning--quick-revision-notes": "/resources/read/dl-quick-revision-notes",
  "deep-learning--cheat-sheet": "/resources/read/dl-cheat-sheet",
  "generative-ai--beginner-guide": "/resources/read/genai-beginner-guide",
  "generative-ai--complete-tutorial": "/resources/read/genai-complete-tutorial",
  "generative-ai--interview-questions": "/resources/read/genai-interview-questions",
 "generative-ai--practice-questions": "/resources/read/genai-practice-questions",
 "generative-ai--real-world-case-study": "/resources/read/genai-real-world-case-study",
 "generative-ai--frequently-asked-questions": "/resources/read/genai-frequently-asked-questions",
 "prompt-engineering--advanced-concepts": "/resources/read/pe-advanced-concepts",
 "prompt-engineering--glossary": "/resources/read/pe-glossary",
 "prompt-engineering--reference-guide": "/resources/read/pe-reference-guide",
 "prompt-engineering--frequently-asked-questions": "/resources/read/pe-frequently-asked-questions",
 "prompt-engineering--learning-roadmap": "/resources/read/pe-learning-roadmap",
 "prompt-engineering--tips-tricks": "/resources/read/pe-tips-tricks",
 "prompt-engineering--beginner-guide": "/resources/read/pe-beginner-guide",
 "prompt-engineering--complete-tutorial": "/resources/read/pe-complete-tutorial",
 "prompt-engineering--step-by-step-learning-guide": "/resources/read/pe-step-by-step-learning-guide",
 "prompt-engineering--pdf-notes": "/resources/read/pe-pdf-notes",
 "prompt-engineering--quick-revision-notes": "/resources/read/pe-quick-revision-notes",
 "prompt-engineering--cheat-sheet": "/resources/read/pe-cheat-sheet",
 "prompt-engineering--sample-exercises": "/resources/read/pe-sample-exercises",
 "prompt-engineering--project-guide": "/resources/read/pe-project-guide",
 "prompt-engineering--project-case-study": "/resources/read/pe-project-case-study",
 "prompt-engineering--interview-questions": "/resources/read/pe-interview-questions",
 "prompt-engineering--practice-questions": "/resources/read/pe-practice-questions",
 "prompt-engineering--answer-key": "/resources/read/pe-answer-key",
 "prompt-engineering--real-world-case-study": "/resources/read/pe-real-world-case-study",
 "prompt-engineering--best-practices": "/resources/read/pe-best-practices",
 "prompt-engineering--common-mistakes": "/resources/read/pe-common-mistakes",
  "dbms--frequently-asked-questions": "/resources/read/dbms-frequently-asked-questions",
  "dbms--learning-roadmap": "/resources/read/dbms-learning-roadmap",
  "dbms--tips-tricks": "/resources/read/dbms-tips-tricks",
  "dbms--advanced-concepts": "/resources/read/dbms-advanced-concepts",
  "dbms--glossary": "/resources/read/dbms-glossary",
  "dbms--reference-guide": "/resources/read/dbms-reference-guide",
  "dbms--interview-questions": "/resources/read/dbms-interview-questions",
  "dbms--practice-questions": "/resources/read/dbms-practice-questions",
  "dbms--answer-key": "/resources/read/dbms-answer-key",
  "dbms--beginner-guide": "/resources/read/dbms-beginner-guide",
  "dbms--complete-tutorial": "/resources/read/dbms-complete-tutorial",
  "dbms--step-by-step-learning-guide": "/resources/read/dbms-step-by-step-learning-guide",
  "dbms--pdf-notes": "/resources/read/dbms-pdf-notes",
  "dbms--quick-revision-notes": "/resources/read/dbms-quick-revision-notes",
  "dbms--cheat-sheet": "/resources/read/dbms-cheat-sheet",
  "dbms--sample-exercises": "/resources/read/dbms-sample-exercises",
  "dbms--project-guide": "/resources/read/dbms-project-guide",
   "dbms--project-case-study": "/resources/read/dbms-project-case-study",
   "dbms--real-world-case-study": "/resources/read/dbms-real-world-case-study",
   "dbms--best-practices": "/resources/read/dbms-best-practices",
   "dbms--common-mistakes": "/resources/read/dbms-common-mistakes",
   "system-design--beginner-guide": "/resources/read/sd-beginner-guide",
   "system-design--complete-tutorial": "/resources/read/sd-complete-tutorial",
   "system-design--step-by-step-learning-guide": "/resources/read/sd-step-by-step-learning-guide",
   "system-design--pdf-notes": "/resources/read/sd-pdf-notes",
   "system-design--quick-revision-notes": "/resources/read/sd-quick-revision-notes",
   "system-design--cheat-sheet": "/resources/read/sd-cheat-sheet",
   "system-design--frequently-asked-questions": "/resources/read/sd-frequently-asked-questions",
   "system-design--learning-roadmap": "/resources/read/sd-learning-roadmap",
   "system-design--tips-tricks": "/resources/read/sd-tips-tricks",
   "system-design--advanced-concepts": "/resources/read/sd-advanced-concepts",
   "system-design--glossary": "/resources/read/sd-glossary",
   "system-design--reference-guide": "/resources/read/sd-reference-guide",
   "go--beginner-guide": "/resources/read/go-beginner-guide",
   "go--complete-tutorial": "/resources/read/go-complete-tutorial",
   "go--step-by-step-learning-guide": "/resources/read/go-step-by-step-learning-guide",
   "go--pdf-notes": "/resources/read/go-pdf-notes",
   "go--quick-revision-notes": "/resources/read/go-quick-revision-notes",
   "go--cheat-sheet": "/resources/read/go-cheat-sheet",
   "go--interview-questions": "/resources/read/go-interview-questions",
   "go--practice-questions": "/resources/read/go-practice-questions",
   "go--answer-key": "/resources/read/go-answer-key",
   "go--sample-exercises": "/resources/read/go-sample-exercises",
   "go--project-guide": "/resources/read/go-project-guide",
   "go--project-case-study": "/resources/read/go-project-case-study",
   "go--real-world-case-study": "/resources/read/go-real-world-case-study",
   "go--best-practices": "/resources/read/go-best-practices",
   "go--common-mistakes": "/resources/read/go-common-mistakes",
   "go--frequently-asked-questions": "/resources/read/go-frequently-asked-questions",
   "go--learning-roadmap": "/resources/read/go-learning-roadmap",
   "go--tips-and-tricks": "/resources/read/go-tips-and-tricks",
   "go--advanced-concepts": "/resources/read/go-advanced-concepts",
   "go--glossary": "/resources/read/go-glossary",
   "go--reference-guide": "/resources/read/go-reference-guide",
   "rust--beginner-guide": "/resources/read/rust-beginner-guide",
   "rust--complete-tutorial": "/resources/read/rust-complete-tutorial",
   "rust--step-by-step-learning-guide": "/resources/read/rust-step-by-step-learning-guide",
   "rust--pdf-notes": "/resources/read/rust-pdf-notes",
   "rust--quick-revision-notes": "/resources/read/rust-quick-revision-notes",
   "rust--cheat-sheet": "/resources/read/rust-cheat-sheet",
   "rust--interview-questions": "/resources/read/rust-interview-questions",
   "rust--practice-questions": "/resources/read/rust-practice-questions",
   "rust--answer-key": "/resources/read/rust-answer-key",
   "rust--sample-exercises": "/resources/read/rust-sample-exercises",
   "rust--project-guide": "/resources/read/rust-project-guide",
   "rust--project-case-study": "/resources/read/rust-project-case-study",
   "rust--real-world-case-study": "/resources/read/rust-real-world-case-study",
   "rust--best-practices": "/resources/read/rust-best-practices",
   "rust--common-mistakes": "/resources/read/rust-common-mistakes",
   "rust--frequently-asked-questions": "/resources/read/rust-frequently-asked-questions",
   "rust--learning-roadmap": "/resources/read/rust-learning-roadmap",
   "rust--tips-and-tricks": "/resources/read/rust-tips-and-tricks",
   "rust--advanced-concepts": "/resources/read/rust-advanced-concepts",
   "rust--glossary": "/resources/read/rust-glossary",
   "rust--reference-guide": "/resources/read/rust-reference-guide",
   "react--beginner-guide": "/resources/read/react-beginner-guide",
   "react--complete-tutorial": "/resources/read/react-complete-tutorial",
   "react--step-by-step-learning-guide": "/resources/read/react-step-by-step-learning-guide",
   "react--pdf-notes": "/resources/read/react-pdf-notes",
   "react--quick-revision-notes": "/resources/read/react-quick-revision-notes",
   "react--cheat-sheet": "/resources/read/react-cheat-sheet",
   "react--interview-questions": "/resources/read/react-interview-questions",
   "react--practice-questions": "/resources/read/react-practice-questions",
    "react--answer-key": "/resources/read/react-answer-key",
    "react--sample-exercises": "/resources/read/react-sample-exercises",
    "react--project-guide": "/resources/read/react-project-guide",
    "react--project-case-study": "/resources/read/react-project-case-study",
    "react--real-world-case-study": "/resources/read/react-real-world-case-study",
    "react--best-practices": "/resources/read/react-best-practices",
    "react--common-mistakes": "/resources/read/react-common-mistakes",
    "react--frequently-asked-questions": "/resources/read/react-frequently-asked-questions",
    "react--learning-roadmap": "/resources/read/react-learning-roadmap",
    "react--tips-and-tricks": "/resources/read/react-tips-and-tricks",
    "react--advanced-concepts": "/resources/read/react-advanced-concepts",
    "react--glossary": "/resources/read/react-glossary",
    "react--reference-guide": "/resources/read/react-reference-guide",
    "computer-networks--beginner-guide": "/resources/read/computer-networks-beginner-guide",
    "computer-networks--complete-tutorial": "/resources/read/computer-networks-complete-tutorial",
    "computer-networks--step-by-step-learning-guide": "/resources/read/computer-networks-step-by-step-learning-guide",
    "computer-networks--pdf-notes": "/resources/read/computer-networks-pdf-notes",
    "computer-networks--quick-revision-notes": "/resources/read/computer-networks-quick-revision-notes",
    "computer-networks--cheat-sheet": "/resources/read/computer-networks-cheat-sheet",
    "computer-networks--interview-questions": "/resources/read/computer-networks-interview-questions",
    "computer-networks--practice-questions": "/resources/read/computer-networks-practice-questions",
    "computer-networks--answer-key": "/resources/read/computer-networks-answer-key",
    "computer-networks--sample-exercises": "/resources/read/computer-networks-sample-exercises",
    "computer-networks--project-guide": "/resources/read/computer-networks-project-guide",
    "computer-networks--project-case-study": "/resources/read/computer-networks-project-case-study",
    "computer-networks--real-world-case-study": "/resources/read/computer-networks-real-world-case-study",
    "computer-networks--best-practices": "/resources/read/computer-networks-best-practices",
    "computer-networks--common-mistakes": "/resources/read/computer-networks-common-mistakes",
    "computer-networks--frequently-asked-questions": "/resources/read/computer-networks-frequently-asked-questions",
    "computer-networks--learning-roadmap": "/resources/read/computer-networks-learning-roadmap",
    "computer-networks--tips-and-tricks": "/resources/read/computer-networks-tips-and-tricks",
    "computer-networks--advanced-concepts": "/resources/read/computer-networks-advanced-concepts",
    "computer-networks--glossary": "/resources/read/computer-networks-glossary",
    "computer-networks--reference-guide": "/resources/read/computer-networks-reference-guide",
    "javascript--beginner-guide": "/resources/read/javascript-beginner-guide",
    "javascript--complete-tutorial": "/resources/read/javascript-complete-tutorial",
    "javascript--step-by-step-learning-guide": "/resources/read/javascript-step-by-step-learning-guide",
    "javascript--pdf-notes": "/resources/read/javascript-pdf-notes",
    "javascript--quick-revision-notes": "/resources/read/javascript-quick-revision-notes",
    "javascript--cheat-sheet": "/resources/read/javascript-cheat-sheet",
    "javascript--interview-questions": "/resources/read/javascript-interview-questions",
    "javascript--practice-questions": "/resources/read/javascript-practice-questions",
    "javascript--answer-key": "/resources/read/javascript-answer-key",
    "javascript--sample-exercises": "/resources/read/javascript-sample-exercises",
    "javascript--project-guide": "/resources/read/javascript-project-guide",
    "javascript--project-case-study": "/resources/read/javascript-project-case-study",
    "javascript--real-world-case-study": "/resources/read/javascript-real-world-case-study",
    "javascript--best-practices": "/resources/read/javascript-best-practices",
    "javascript--common-mistakes": "/resources/read/javascript-common-mistakes",
    "javascript--frequently-asked-questions": "/resources/read/javascript-frequently-asked-questions",
    "javascript--learning-roadmap": "/resources/read/javascript-learning-roadmap",
    "javascript--tips-and-tricks": "/resources/read/javascript-tips-and-tricks",
    "javascript--advanced-concepts": "/resources/read/javascript-advanced-concepts",
    "javascript--glossary": "/resources/read/javascript-glossary",
    "javascript--reference-guide": "/resources/read/javascript-reference-guide",
    "html5--beginner-guide": "/resources/read/html5-beginner-guide",
    "html5--complete-tutorial": "/resources/read/html5-complete-tutorial",
    "html5--step-by-step-learning-guide": "/resources/read/html5-step-by-step-learning-guide",
    "html5--pdf-notes": "/resources/read/html5-pdf-notes",
    "html5--quick-revision-notes": "/resources/read/html5-quick-revision-notes",
    "html5--cheat-sheet": "/resources/read/html5-cheat-sheet",
    "html5--interview-questions": "/resources/read/html5-interview-questions",
    "html5--practice-questions": "/resources/read/html5-practice-questions",
    "html5--answer-key": "/resources/read/html5-answer-key",
    "html5--sample-exercises": "/resources/read/html5-sample-exercises",
    "html5--project-guide": "/resources/read/html5-project-guide",
    "html5--project-case-study": "/resources/read/html5-project-case-study",
    "html5--real-world-case-study": "/resources/read/html5-real-world-case-study",
    "html5--best-practices": "/resources/read/html5-best-practices",
    "html5--common-mistakes": "/resources/read/html5-common-mistakes",
    "html5--frequently-asked-questions": "/resources/read/html5-frequently-asked-questions",
    "html5--learning-roadmap": "/resources/read/html5-learning-roadmap",
    "html5--tips-and-tricks": "/resources/read/html5-tips-and-tricks",
    "html5--advanced-concepts": "/resources/read/html5-advanced-concepts",
    "html5--glossary": "/resources/read/html5-glossary",
    "html5--reference-guide": "/resources/read/html5-reference-guide",
    "operating-systems--beginner-guide": "/resources/read/operating-systems-beginner-guide",
    "operating-systems--complete-tutorial": "/resources/read/operating-systems-complete-tutorial",
    "operating-systems--step-by-step-learning-guide": "/resources/read/operating-systems-step-by-step-learning-guide",
    "operating-systems--pdf-notes": "/resources/read/operating-systems-pdf-notes",
    "operating-systems--quick-revision-notes": "/resources/read/operating-systems-quick-revision-notes",
    "operating-systems--cheat-sheet": "/resources/read/operating-systems-cheat-sheet",
    "operating-systems--interview-questions": "/resources/read/operating-systems-interview-questions",
    "operating-systems--practice-questions": "/resources/read/operating-systems-practice-questions",
    "operating-systems--answer-key": "/resources/read/operating-systems-answer-key",
    "operating-systems--sample-exercises": "/resources/read/operating-systems-sample-exercises",
    "operating-systems--project-guide": "/resources/read/operating-systems-project-guide",
    "operating-systems--project-case-study": "/resources/read/operating-systems-project-case-study",
    "operating-systems--real-world-case-study": "/resources/read/operating-systems-real-world-case-study",
    "operating-systems--best-practices": "/resources/read/operating-systems-best-practices",
    "operating-systems--common-mistakes": "/resources/read/operating-systems-common-mistakes",
    "operating-systems--frequently-asked-questions": "/resources/read/operating-systems-frequently-asked-questions",
    "operating-systems--learning-roadmap": "/resources/read/operating-systems-learning-roadmap",
    "operating-systems--tips-and-tricks": "/resources/read/operating-systems-tips-and-tricks",
    "operating-systems--advanced-concepts": "/resources/read/operating-systems-advanced-concepts",
    "operating-systems--glossary": "/resources/read/operating-systems-glossary",
    "operating-systems--reference-guide": "/resources/read/operating-systems-reference-guide",
    "dsa--beginner-guide": "/resources/read/dsa-beginner-guide",
    "dsa--complete-tutorial": "/resources/read/dsa-complete-tutorial",
    "dsa--step-by-step-learning-guide": "/resources/read/dsa-step-by-step-learning-guide",
    "dsa--pdf-notes": "/resources/read/dsa-pdf-notes",
    "dsa--quick-revision-notes": "/resources/read/dsa-quick-revision-notes",
    "dsa--cheat-sheet": "/resources/read/dsa-cheat-sheet",
    "dsa--interview-questions": "/resources/read/dsa-interview-questions",
    "dsa--practice-questions": "/resources/read/dsa-practice-questions",
    "dsa--answer-key": "/resources/read/dsa-answer-key",
    "dsa--sample-exercises": "/resources/read/dsa-sample-exercises",
    "dsa--project-guide": "/resources/read/dsa-project-guide",
    "dsa--project-case-study": "/resources/read/dsa-project-case-study",
    "dsa--real-world-case-study": "/resources/read/dsa-real-world-case-study",
    "dsa--best-practices": "/resources/read/dsa-best-practices",
    "dsa--common-mistakes": "/resources/read/dsa-common-mistakes",
    "dsa--frequently-asked-questions": "/resources/read/dsa-frequently-asked-questions",
    "dsa--learning-roadmap": "/resources/read/dsa-learning-roadmap",
    "dsa--tips-and-tricks": "/resources/read/dsa-tips-and-tricks",
    "dsa--advanced-concepts": "/resources/read/dsa-advanced-concepts",
    "dsa--glossary": "/resources/read/dsa-glossary",
    "dsa--reference-guide": "/resources/read/dsa-reference-guide",
    "figma--beginner-guide": "/resources/read/figma-beginner-guide",
    "figma--complete-tutorial": "/resources/read/figma-complete-tutorial",
    "figma--step-by-step-learning-guide": "/resources/read/figma-step-by-step-learning-guide",
    "figma--pdf-notes": "/resources/read/figma-pdf-notes",
    "figma--quick-revision-notes": "/resources/read/figma-quick-revision-notes",
    "figma--cheat-sheet": "/resources/read/figma-cheat-sheet",
    "figma--interview-questions": "/resources/read/figma-interview-questions",
    "figma--practice-questions": "/resources/read/figma-practice-questions",
    "figma--answer-key": "/resources/read/figma-answer-key",
    "figma--sample-exercises": "/resources/read/figma-sample-exercises",
    "figma--project-guide": "/resources/read/figma-project-guide",
    "figma--project-case-study": "/resources/read/figma-project-case-study",
    "figma--real-world-case-study": "/resources/read/figma-real-world-case-study",
    "figma--best-practices": "/resources/read/figma-best-practices",
    "figma--common-mistakes": "/resources/read/figma-common-mistakes",
    "figma--frequently-asked-questions": "/resources/read/figma-frequently-asked-questions",
    "figma--learning-roadmap": "/resources/read/figma-learning-roadmap",
    "figma--tips-tricks": "/resources/read/figma-tips-and-tricks",
    "figma--advanced-concepts": "/resources/read/figma-advanced-concepts",
    "figma--glossary": "/resources/read/figma-glossary",
    "figma--reference-guide": "/resources/read/figma-reference-guide",
    "ux-design--beginner-guide": "/resources/read/ux-design-beginner-guide",
    "ux-design--complete-tutorial": "/resources/read/ux-design-complete-tutorial",
    "ux-design--step-by-step-learning-guide": "/resources/read/ux-design-step-by-step-learning-guide",
    "ux-design--pdf-notes": "/resources/read/ux-design-pdf-notes",
    "ux-design--quick-revision-notes": "/resources/read/ux-design-quick-revision-notes",
    "ux-design--cheat-sheet": "/resources/read/ux-design-cheat-sheet",
    "ux-design--interview-questions": "/resources/read/ux-design-interview-questions",
    "ux-design--practice-questions": "/resources/read/ux-design-practice-questions",
    "ux-design--answer-key": "/resources/read/ux-design-answer-key",
    "ux-design--real-world-case-study": "/resources/read/ux-design-real-world-case-study",
    "ux-design--best-practices": "/resources/read/ux-design-best-practices",
    "ux-design--common-mistakes": "/resources/read/ux-design-common-mistakes",
    "ux-design--frequently-asked-questions": "/resources/read/ux-design-frequently-asked-questions",
    "ux-design--learning-roadmap": "/resources/read/ux-design-learning-roadmap",
    "ux-design--tips-tricks": "/resources/read/ux-design-tips-and-tricks",
    "ux-design--advanced-concepts": "/resources/read/ux-design-advanced-concepts",
    "ux-design--glossary": "/resources/read/ux-design-glossary",
    "ux-design--reference-guide": "/resources/read/ux-design-reference-guide",
    "penetration-testing--beginner-guide": "/resources/read/penetration-testing-beginner-guide",
    "penetration-testing--complete-tutorial": "/resources/read/penetration-testing-complete-tutorial",
    "penetration-testing--step-by-step-learning-guide": "/resources/read/penetration-testing-step-by-step-learning-guide",
    "penetration-testing--pdf-notes": "/resources/read/penetration-testing-pdf-notes",
    "penetration-testing--quick-revision-notes": "/resources/read/penetration-testing-quick-revision-notes",
    "penetration-testing--cheat-sheet": "/resources/read/penetration-testing-cheat-sheet",
    "penetration-testing--interview-questions": "/resources/read/penetration-testing-interview-questions",
    "penetration-testing--practice-questions": "/resources/read/penetration-testing-practice-questions",
    "penetration-testing--answer-key": "/resources/read/penetration-testing-answer-key",
    "penetration-testing--sample-exercises": "/resources/read/penetration-testing-sample-exercises",
    "penetration-testing--project-guide": "/resources/read/penetration-testing-project-guide",
    "penetration-testing--project-case-study": "/resources/read/penetration-testing-project-case-study",
    "penetration-testing--frequently-asked-questions": "/resources/read/penetration-testing-frequently-asked-questions",
    "penetration-testing--learning-roadmap": "/resources/read/penetration-testing-learning-roadmap",
    "penetration-testing--tips-tricks": "/resources/read/penetration-testing-tips-tricks",
    "penetration-testing--advanced-concepts": "/resources/read/penetration-testing-advanced-concepts",
    "penetration-testing--glossary": "/resources/read/penetration-testing-glossary",
    "penetration-testing--reference-guide": "/resources/read/penetration-testing-reference-guide",
    "network-security--beginner-guide": "/resources/read/network-security-beginner-guide",
    "network-security--complete-tutorial": "/resources/read/network-security-complete-tutorial",
    "network-security--step-by-step-learning-guide": "/resources/read/network-security-step-by-step-learning-guide",
    "network-security--pdf-notes": "/resources/read/network-security-pdf-notes",
    "network-security--quick-revision-notes": "/resources/read/network-security-quick-revision-notes",
    "network-security--cheat-sheet": "/resources/read/network-security-cheat-sheet",
    "network-security--interview-questions": "/resources/read/network-security-interview-questions",
    "network-security--practice-questions": "/resources/read/network-security-practice-questions",
    "network-security--answer-key": "/resources/read/network-security-answer-key",
    "network-security--real-world-case-study": "/resources/read/network-security-real-world-case-study",
    "network-security--best-practices": "/resources/read/network-security-best-practices",
    "network-security--common-mistakes": "/resources/read/network-security-common-mistakes",
    "network-security--frequently-asked-questions": "/resources/read/network-security-frequently-asked-questions",
    "network-security--learning-roadmap": "/resources/read/network-security-learning-roadmap",
    "network-security--tips-tricks": "/resources/read/network-security-tips-tricks",
    "network-security--advanced-concepts": "/resources/read/network-security-advanced-concepts",
    "network-security--glossary": "/resources/read/network-security-glossary",
    "network-security--reference-guide": "/resources/read/network-security-reference-guide",
    "ethical-hacking--beginner-guide": "/resources/read/ethical-hacking-beginner-guide",
    "ethical-hacking--complete-tutorial": "/resources/read/ethical-hacking-complete-tutorial",
    "ethical-hacking--step-by-step-learning-guide": "/resources/read/ethical-hacking-step-by-step-learning-guide",
    "ethical-hacking--pdf-notes": "/resources/read/ethical-hacking-pdf-notes",
    "ethical-hacking--quick-revision-notes": "/resources/read/ethical-hacking-quick-revision-notes",
    "ethical-hacking--cheat-sheet": "/resources/read/ethical-hacking-cheat-sheet",
    "ethical-hacking--interview-questions": "/resources/read/ethical-hacking-interview-questions",
    "ethical-hacking--practice-questions": "/resources/read/ethical-hacking-practice-questions",
    "ethical-hacking--answer-key": "/resources/read/ethical-hacking-answer-key",
    "ethical-hacking--sample-exercises": "/resources/read/ethical-hacking-sample-exercises",
    "ethical-hacking--project-guide": "/resources/read/ethical-hacking-project-guide",
    "ethical-hacking--project-case-study": "/resources/read/ethical-hacking-project-case-study",
    "ethical-hacking--real-world-case-study": "/resources/read/ethical-hacking-real-world-case-study",
    "ethical-hacking--best-practices": "/resources/read/ethical-hacking-best-practices",
    "ethical-hacking--common-mistakes": "/resources/read/ethical-hacking-common-mistakes",
    "ethical-hacking--frequently-asked-questions": "/resources/read/ethical-hacking-frequently-asked-questions",
    "ethical-hacking--learning-roadmap": "/resources/read/ethical-hacking-learning-roadmap",
    "ethical-hacking--tips-tricks": "/resources/read/ethical-hacking-tips-tricks",
    "ethical-hacking--advanced-concepts": "/resources/read/ethical-hacking-advanced-concepts",
    "ethical-hacking--glossary": "/resources/read/ethical-hacking-glossary",
    "ethical-hacking--reference-guide": "/resources/read/ethical-hacking-reference-guide",
    "cyber-security--beginner-guide": "/resources/read/cyber-security-beginner-guide",
    "cyber-security--complete-tutorial": "/resources/read/cyber-security-complete-tutorial",
    "cyber-security--step-by-step-learning-guide": "/resources/read/cyber-security-step-by-step-learning-guide",
    "cyber-security--pdf-notes": "/resources/read/cyber-security-pdf-notes",
    "cyber-security--quick-revision-notes": "/resources/read/cyber-security-quick-revision-notes",
    "cyber-security--cheat-sheet": "/resources/read/cyber-security-cheat-sheet",
    "cyber-security--interview-questions": "/resources/read/cyber-security-interview-questions",
    "cyber-security--practice-questions": "/resources/read/cyber-security-practice-questions",
    "cyber-security--answer-key": "/resources/read/cyber-security-answer-key",
    "cyber-security--sample-exercises": "/resources/read/cyber-security-sample-exercises",
    "cyber-security--project-guide": "/resources/read/cyber-security-project-guide",
    "cyber-security--project-case-study": "/resources/read/cyber-security-project-case-study",
    "cyber-security--real-world-case-study": "/resources/read/cyber-security-real-world-case-study",
    "cyber-security--best-practices": "/resources/read/cyber-security-best-practices",
    "cyber-security--common-mistakes": "/resources/read/cyber-security-common-mistakes",
    "cyber-security--frequently-asked-questions": "/resources/read/cyber-security-frequently-asked-questions",
    "cyber-security--learning-roadmap": "/resources/read/cyber-security-learning-roadmap",
    "cyber-security--tips-tricks": "/resources/read/cyber-security-tips-tricks",
    "cyber-security--advanced-concepts": "/resources/read/cyber-security-advanced-concepts",
    "cyber-security--glossary": "/resources/read/cyber-security-glossary",
    "cyber-security--reference-guide": "/resources/read/cyber-security-reference-guide",
    "devops--beginner-guide": "/resources/read/devops-beginner-guide",
    "devops--complete-tutorial": "/resources/read/devops-complete-tutorial",
    "devops--step-by-step-learning-guide": "/resources/read/devops-step-by-step-learning-guide",
    "devops--pdf-notes": "/resources/read/devops-pdf-notes",
    "devops--quick-revision-notes": "/resources/read/devops-quick-revision-notes",
    "devops--cheat-sheet": "/resources/read/devops-cheat-sheet",
    "devops--interview-questions": "/resources/read/devops-interview-questions",
    "devops--practice-questions": "/resources/read/devops-practice-questions",
    "devops--answer-key": "/resources/read/devops-answer-key",
    "devops--sample-exercises": "/resources/read/devops-sample-exercises",
    "devops--project-guide": "/resources/read/devops-project-guide",
    "devops--project-case-study": "/resources/read/devops-project-case-study",
    "devops--real-world-case-study": "/resources/read/devops-real-world-case-study",
    "devops--best-practices": "/resources/read/devops-best-practices",
    "devops--common-mistakes": "/resources/read/devops-common-mistakes",
    "devops--frequently-asked-questions": "/resources/read/devops-frequently-asked-questions",
    "devops--learning-roadmap": "/resources/read/devops-learning-roadmap",
    "devops--tips-tricks": "/resources/read/devops-tips-tricks",
    "devops--advanced-concepts": "/resources/read/devops-advanced-concepts",
    "devops--glossary": "/resources/read/devops-glossary",
    "devops--reference-guide": "/resources/read/devops-reference-guide",
    "azure--beginner-guide": "/resources/read/azure-beginner-guide",
    "azure--complete-tutorial": "/resources/read/azure-complete-tutorial",
    "azure--step-by-step-learning-guide": "/resources/read/azure-step-by-step-learning-guide",
    "azure--pdf-notes": "/resources/read/azure-pdf-notes",
    "azure--quick-revision-notes": "/resources/read/azure-quick-revision-notes",
    "azure--cheat-sheet": "/resources/read/azure-cheat-sheet",
    "azure--interview-questions": "/resources/read/azure-interview-questions",
    "azure--practice-questions": "/resources/read/azure-practice-questions",
    "azure--answer-key": "/resources/read/azure-answer-key",
    "azure--sample-exercises": "/resources/read/azure-sample-exercises",
    "azure--project-guide": "/resources/read/azure-project-guide",
    "azure--project-case-study": "/resources/read/azure-project-case-study",
    "azure--real-world-case-study": "/resources/read/azure-real-world-case-study",
    "azure--best-practices": "/resources/read/azure-best-practices",
    "azure--common-mistakes": "/resources/read/azure-common-mistakes",
    "azure--frequently-asked-questions": "/resources/read/azure-frequently-asked-questions",
    "azure--learning-roadmap": "/resources/read/azure-learning-roadmap",
    "azure--tips-tricks": "/resources/read/azure-tips-tricks",
    "azure--advanced-concepts": "/resources/read/azure-advanced-concepts",
    "azure--glossary": "/resources/read/azure-glossary",
    "azure--reference-guide": "/resources/read/azure-reference-guide",
    "gcp--beginner-guide": "/resources/read/gcp-beginner-guide",
    "gcp--complete-tutorial": "/resources/read/gcp-complete-tutorial",
    "gcp--step-by-step-learning-guide": "/resources/read/gcp-step-by-step-learning-guide",
    "gcp--pdf-notes": "/resources/read/gcp-pdf-notes",
    "gcp--quick-revision-notes": "/resources/read/gcp-quick-revision-notes",
    "gcp--cheat-sheet": "/resources/read/gcp-cheat-sheet",
    "gcp--interview-questions": "/resources/read/gcp-interview-questions",
    "gcp--practice-questions": "/resources/read/gcp-practice-questions",
    "gcp--answer-key": "/resources/read/gcp-answer-key",
    "gcp--sample-exercises": "/resources/read/gcp-sample-exercises",
    "gcp--project-guide": "/resources/read/gcp-project-guide",
    "gcp--project-case-study": "/resources/read/gcp-project-case-study",
    "gcp--real-world-case-study": "/resources/read/gcp-real-world-case-study",
    "gcp--best-practices": "/resources/read/gcp-best-practices",
    "gcp--common-mistakes": "/resources/read/gcp-common-mistakes",
    "gcp--frequently-asked-questions": "/resources/read/gcp-frequently-asked-questions",
    "gcp--learning-roadmap": "/resources/read/gcp-learning-roadmap",
    "gcp--tips-tricks": "/resources/read/gcp-tips-tricks",
    "gcp--advanced-concepts": "/resources/read/gcp-advanced-concepts",
    "gcp--glossary": "/resources/read/gcp-glossary",
    "gcp--reference-guide": "/resources/read/gcp-reference-guide",
    "aws--beginner-guide": "/resources/read/aws-beginner-guide",
    "aws--complete-tutorial": "/resources/read/aws-complete-tutorial",
    "aws--step-by-step-learning-guide": "/resources/read/aws-step-by-step-learning-guide",
    "aws--pdf-notes": "/resources/read/aws-pdf-notes",
    "aws--quick-revision-notes": "/resources/read/aws-quick-revision-notes",
    "aws--cheat-sheet": "/resources/read/aws-cheat-sheet",
    "aws--interview-questions": "/resources/read/aws-interview-questions",
    "aws--practice-questions": "/resources/read/aws-practice-questions",
    "aws--answer-key": "/resources/read/aws-answer-key",
    "aws--sample-exercises": "/resources/read/aws-sample-exercises",
    "aws--project-guide": "/resources/read/aws-project-guide",
    "aws--project-case-study": "/resources/read/aws-project-case-study",
    "aws--real-world-case-study": "/resources/read/aws-real-world-case-study",
    "aws--best-practices": "/resources/read/aws-best-practices",
    "aws--common-mistakes": "/resources/read/aws-common-mistakes",
    "aws--frequently-asked-questions": "/resources/read/aws-frequently-asked-questions",
    "aws--learning-roadmap": "/resources/read/aws-learning-roadmap",
    "aws--tips-tricks": "/resources/read/aws-tips-tricks",
    "aws--advanced-concepts": "/resources/read/aws-advanced-concepts",
    "aws--glossary": "/resources/read/aws-glossary",
    "aws--reference-guide": "/resources/read/aws-reference-guide",
    "ai-agents--beginner-guide": "/resources/read/ai-agents-beginner-guide",
    "ai-agents--complete-tutorial": "/resources/read/ai-agents-complete-tutorial",
    "ai-agents--step-by-step-learning-guide": "/resources/read/ai-agents-step-by-step-learning-guide",
    "ai-agents--pdf-notes": "/resources/read/ai-agents-pdf-notes",
    "ai-agents--quick-revision-notes": "/resources/read/ai-agents-quick-revision-notes",
    "ai-agents--cheat-sheet": "/resources/read/ai-agents-cheat-sheet",
    "ai-agents--interview-questions": "/resources/read/ai-agents-interview-questions",
    "ai-agents--practice-questions": "/resources/read/ai-agents-practice-questions",
    "ai-agents--answer-key": "/resources/read/ai-agents-answer-key",
    "ai-agents--sample-exercises": "/resources/read/ai-agents-sample-exercises",
    "ai-agents--project-guide": "/resources/read/ai-agents-project-guide",
    "ai-agents--project-case-study": "/resources/read/ai-agents-project-case-study",
    "ai-agents--real-world-case-study": "/resources/read/ai-agents-real-world-case-study",
    "ai-agents--best-practices": "/resources/read/ai-agents-best-practices",
    "ai-agents--common-mistakes": "/resources/read/ai-agents-common-mistakes",
    "ai-agents--frequently-asked-questions": "/resources/read/ai-agents-frequently-asked-questions",
    "ai-agents--learning-roadmap": "/resources/read/ai-agents-learning-roadmap",
    "ai-agents--tips-tricks": "/resources/read/ai-agents-tips-tricks",
    "ai-agents--advanced-concepts": "/resources/read/ai-agents-advanced-concepts",
    "ai-agents--glossary": "/resources/read/ai-agents-glossary",
    "ai-agents--reference-guide": "/resources/read/ai-agents-reference-guide",
    "python--beginner-guide": "/resources/read/python-beginner-guide",
    "python--complete-tutorial": "/resources/read/python-complete-tutorial",
    "python--step-by-step-learning-guide": "/resources/read/python-step-by-step-learning-guide",
    "python--pdf-notes": "/resources/read/python-pdf-notes",
    "python--quick-revision-notes": "/resources/read/python-quick-revision-notes",
    "python--cheat-sheet": "/resources/read/python-cheat-sheet",
    "python--interview-questions": "/resources/read/python-interview-questions",
    "python--practice-questions": "/resources/read/python-practice-questions",
    "python--answer-key": "/resources/read/python-answer-key",
    "python--sample-exercises": "/resources/read/python-sample-exercises",
    "python--project-guide": "/resources/read/python-project-guide",
    "python--project-case-study": "/resources/read/python-project-case-study",
    "python--real-world-case-study": "/resources/read/python-real-world-case-study",
    "python--best-practices": "/resources/read/python-best-practices",
    "python--common-mistakes": "/resources/read/python-common-mistakes",
    "python--frequently-asked-questions": "/resources/read/python-frequently-asked-questions",
    "python--learning-roadmap": "/resources/read/python-learning-roadmap",
    "python--tips-tricks": "/resources/read/python-tips-tricks",
    "python--advanced-concepts": "/resources/read/python-advanced-concepts",
    "python--glossary": "/resources/read/python-glossary",
    "python--reference-guide": "/resources/read/python-reference-guide",
    "java--beginner-guide": "/resources/read/java-beginner-guide",
    "java--complete-tutorial": "/resources/read/java-complete-tutorial",
    "java--step-by-step-learning-guide": "/resources/read/java-step-by-step-learning-guide",
    "java--pdf-notes": "/resources/read/java-pdf-notes",
    "java--quick-revision-notes": "/resources/read/java-quick-revision-notes",
    "java--cheat-sheet": "/resources/read/java-cheat-sheet",
    "java--interview-questions": "/resources/read/java-interview-questions",
    "java--practice-questions": "/resources/read/java-practice-questions",
    "java--answer-key": "/resources/read/java-answer-key",
    "java--sample-exercises": "/resources/read/java-sample-exercises",
    "java--project-guide": "/resources/read/java-project-guide",
    "java--project-case-study": "/resources/read/java-project-case-study",
    "java--real-world-case-study": "/resources/read/java-real-world-case-study",
    "java--best-practices": "/resources/read/java-best-practices",
    "java--common-mistakes": "/resources/read/java-common-mistakes",
    "java--frequently-asked-questions": "/resources/read/java-frequently-asked-questions",
    "java--learning-roadmap": "/resources/read/java-learning-roadmap",
    "java--tips-tricks": "/resources/read/java-tips-tricks",
    "java--advanced-concepts": "/resources/read/java-advanced-concepts",
    "java--glossary": "/resources/read/java-glossary",
    "java--reference-guide": "/resources/read/java-reference-guide",
    "c-programming--beginner-guide": "/resources/read/c-programming-beginner-guide",
    "c-programming--complete-tutorial": "/resources/read/c-programming-complete-tutorial",
    "c-programming--step-by-step-learning-guide": "/resources/read/c-programming-step-by-step-learning-guide",
    "c-programming--pdf-notes": "/resources/read/c-programming-pdf-notes",
    "c-programming--quick-revision-notes": "/resources/read/c-programming-quick-revision-notes",
    "c-programming--cheat-sheet": "/resources/read/c-programming-cheat-sheet",
    "c-programming--interview-questions": "/resources/read/c-programming-interview-questions",
    "c-programming--practice-questions": "/resources/read/c-programming-practice-questions",
    "c-programming--answer-key": "/resources/read/c-programming-answer-key",
    "c-programming--sample-exercises": "/resources/read/c-programming-sample-exercises",
    "c-programming--project-guide": "/resources/read/c-programming-project-guide",
    "c-programming--project-case-study": "/resources/read/c-programming-project-case-study",
    "c-programming--real-world-case-study": "/resources/read/c-programming-real-world-case-study",
    "c-programming--best-practices": "/resources/read/c-programming-best-practices",
    "c-programming--common-mistakes": "/resources/read/c-programming-common-mistakes",
    "c-programming--frequently-asked-questions": "/resources/read/c-programming-frequently-asked-questions",
    "c-programming--learning-roadmap": "/resources/read/c-programming-learning-roadmap",
    "c-programming--tips-tricks": "/resources/read/c-programming-tips-tricks",
    "c-programming--advanced-concepts": "/resources/read/c-programming-advanced-concepts",
    "c-programming--glossary": "/resources/read/c-programming-glossary",
    "c-programming--reference-guide": "/resources/read/c-programming-reference-guide",
    "cpp--beginner-guide": "/resources/read/cpp-beginner-guide",
    "cpp--complete-tutorial": "/resources/read/cpp-complete-tutorial",
    "cpp--step-by-step-learning-guide": "/resources/read/cpp-step-by-step-learning-guide",
    "cpp--pdf-notes": "/resources/read/cpp-pdf-notes",
    "cpp--quick-revision-notes": "/resources/read/cpp-quick-revision-notes",
    "cpp--cheat-sheet": "/resources/read/cpp-cheat-sheet",
    "cpp--interview-questions": "/resources/read/cpp-interview-questions",
    "cpp--practice-questions": "/resources/read/cpp-practice-questions",
    "cpp--answer-key": "/resources/read/cpp-answer-key",
    "cpp--sample-exercises": "/resources/read/cpp-sample-exercises",
    "cpp--project-guide": "/resources/read/cpp-project-guide",
    "cpp--project-case-study": "/resources/read/cpp-project-case-study",
    "cpp--real-world-case-study": "/resources/read/cpp-real-world-case-study",
    "cpp--best-practices": "/resources/read/cpp-best-practices",
    "cpp--common-mistakes": "/resources/read/cpp-common-mistakes",
    "cpp--frequently-asked-questions": "/resources/read/cpp-frequently-asked-questions",
    "cpp--learning-roadmap": "/resources/read/cpp-learning-roadmap",
    "cpp--tips-tricks": "/resources/read/cpp-tips-tricks",
    "cpp--advanced-concepts": "/resources/read/cpp-advanced-concepts",
    "cpp--glossary": "/resources/read/cpp-glossary",
    "cpp--reference-guide": "/resources/read/cpp-reference-guide",
    "sql--beginner-guide": "/resources/read/sql-beginner-guide",
    "sql--complete-tutorial": "/resources/read/sql-complete-tutorial",
    "sql--step-by-step-learning-guide": "/resources/read/sql-step-by-step-learning-guide",
    "sql--pdf-notes": "/resources/read/sql-pdf-notes",
    "sql--quick-revision-notes": "/resources/read/sql-quick-revision-notes",
    "sql--cheat-sheet": "/resources/read/sql-cheat-sheet",
    "sql--interview-questions": "/resources/read/sql-interview-questions",
    "sql--practice-questions": "/resources/read/sql-practice-questions",
    "sql--answer-key": "/resources/read/sql-answer-key",
    "sql--sample-exercises": "/resources/read/sql-sample-exercises",
    "sql--project-guide": "/resources/read/sql-project-guide",
    "sql--project-case-study": "/resources/read/sql-project-case-study",
    "sql--real-world-case-study": "/resources/read/sql-real-world-case-study",
    "sql--best-practices": "/resources/read/sql-best-practices",
    "sql--common-mistakes": "/resources/read/sql-common-mistakes",
    "sql--frequently-asked-questions": "/resources/read/sql-frequently-asked-questions",
    "sql--learning-roadmap": "/resources/read/sql-learning-roadmap",
    "sql--tips-tricks": "/resources/read/sql-tips-tricks",
    "sql--advanced-concepts": "/resources/read/sql-advanced-concepts",
    "sql--glossary": "/resources/read/sql-glossary",
    "sql--reference-guide": "/resources/read/sql-reference-guide",
    "swift-ios--beginner-guide": "/resources/read/swift-ios-beginner-guide",
    "swift-ios--complete-tutorial": "/resources/read/swift-ios-complete-tutorial",
    "swift-ios--step-by-step-learning-guide": "/resources/read/swift-ios-step-by-step-learning-guide",
    "swift-ios--pdf-notes": "/resources/read/swift-ios-pdf-notes",
    "swift-ios--quick-revision-notes": "/resources/read/swift-ios-quick-revision-notes",
    "swift-ios--cheat-sheet": "/resources/read/swift-ios-cheat-sheet",
    "swift-ios--interview-questions": "/resources/read/swift-ios-interview-questions",
    "swift-ios--practice-questions": "/resources/read/swift-ios-practice-questions",
    "swift-ios--answer-key": "/resources/read/swift-ios-answer-key",
    "swift-ios--sample-exercises": "/resources/read/swift-ios-sample-exercises",
    "swift-ios--project-guide": "/resources/read/swift-ios-project-guide",
    "swift-ios--project-case-study": "/resources/read/swift-ios-project-case-study",
    "swift-ios--real-world-case-study": "/resources/read/swift-ios-real-world-case-study",
    "swift-ios--best-practices": "/resources/read/swift-ios-best-practices",
    "swift-ios--common-mistakes": "/resources/read/swift-ios-common-mistakes",
    "swift-ios--frequently-asked-questions": "/resources/read/swift-ios-frequently-asked-questions",
    "swift-ios--learning-roadmap": "/resources/read/swift-ios-learning-roadmap",
    "swift-ios--tips-tricks": "/resources/read/swift-ios-tips-tricks",
    "swift-ios--advanced-concepts": "/resources/read/swift-ios-advanced-concepts",
    "swift-ios--glossary": "/resources/read/swift-ios-glossary",
    "swift-ios--reference-guide": "/resources/read/swift-ios-reference-guide",
    "mysql--beginner-guide": "/resources/read/mysql-beginner-guide",
    "mysql--complete-tutorial": "/resources/read/mysql-complete-tutorial",
    "mysql--step-by-step-learning-guide": "/resources/read/mysql-step-by-step-learning-guide",
    "mysql--pdf-notes": "/resources/read/mysql-pdf-notes",
    "mysql--quick-revision-notes": "/resources/read/mysql-quick-revision-notes",
    "mysql--cheat-sheet": "/resources/read/mysql-cheat-sheet",
    "mysql--interview-questions": "/resources/read/mysql-interview-questions",
    "mysql--practice-questions": "/resources/read/mysql-practice-questions",
    "mysql--answer-key": "/resources/read/mysql-answer-key",
    "mysql--sample-exercises": "/resources/read/mysql-sample-exercises",
    "mysql--project-guide": "/resources/read/mysql-project-guide",
    "mysql--project-case-study": "/resources/read/mysql-project-case-study",
    "mysql--real-world-case-study": "/resources/read/mysql-real-world-case-study",
    "mysql--best-practices": "/resources/read/mysql-best-practices",
    "mysql--common-mistakes": "/resources/read/mysql-common-mistakes",
    "mysql--frequently-asked-questions": "/resources/read/mysql-frequently-asked-questions",
    "mysql--learning-roadmap": "/resources/read/mysql-learning-roadmap",
    "mysql--tips-tricks": "/resources/read/mysql-tips-tricks",
    "mysql--advanced-concepts": "/resources/read/mysql-advanced-concepts",
    "mysql--glossary": "/resources/read/mysql-glossary",
    "mysql--reference-guide": "/resources/read/mysql-reference-guide",
    "kubernetes--beginner-guide": "/resources/read/kubernetes-beginner-guide",
    "kubernetes--complete-tutorial": "/resources/read/kubernetes-complete-tutorial",
    "kubernetes--step-by-step-learning-guide": "/resources/read/kubernetes-step-by-step-learning-guide",
    "kubernetes--pdf-notes": "/resources/read/kubernetes-pdf-notes",
    "kubernetes--quick-revision-notes": "/resources/read/kubernetes-quick-revision-notes",
    "kubernetes--cheat-sheet": "/resources/read/kubernetes-cheat-sheet",
    "kubernetes--interview-questions": "/resources/read/kubernetes-interview-questions",
    "kubernetes--practice-questions": "/resources/read/kubernetes-practice-questions",
    "kubernetes--answer-key": "/resources/read/kubernetes-answer-key",
    "kubernetes--sample-exercises": "/resources/read/kubernetes-sample-exercises",
    "kubernetes--project-guide": "/resources/read/kubernetes-project-guide",
    "kubernetes--project-case-study": "/resources/read/kubernetes-project-case-study",
    "kubernetes--real-world-case-study": "/resources/read/kubernetes-real-world-case-study",
    "kubernetes--best-practices": "/resources/read/kubernetes-best-practices",
    "kubernetes--common-mistakes": "/resources/read/kubernetes-common-mistakes",
    "kubernetes--frequently-asked-questions": "/resources/read/kubernetes-frequently-asked-questions",
    "kubernetes--learning-roadmap": "/resources/read/kubernetes-learning-roadmap",
    "kubernetes--tips-tricks": "/resources/read/kubernetes-tips-tricks",
    "kubernetes--advanced-concepts": "/resources/read/kubernetes-advanced-concepts",
    "kubernetes--glossary": "/resources/read/kubernetes-glossary",
    "kubernetes--reference-guide": "/resources/read/kubernetes-reference-guide",
    "docker--beginner-guide": "/resources/read/docker-beginner-guide",
    "docker--complete-tutorial": "/resources/read/docker-complete-tutorial",
    "docker--step-by-step-learning-guide": "/resources/read/docker-step-by-step-learning-guide",
    "docker--pdf-notes": "/resources/read/docker-pdf-notes",
    "docker--quick-revision-notes": "/resources/read/docker-quick-revision-notes",
    "docker--cheat-sheet": "/resources/read/docker-cheat-sheet",
    "docker--interview-questions": "/resources/read/docker-interview-questions",
    "docker--practice-questions": "/resources/read/docker-practice-questions",
    "docker--answer-key": "/resources/read/docker-answer-key",
    "docker--sample-exercises": "/resources/read/docker-sample-exercises",
    "docker--project-guide": "/resources/read/docker-project-guide",
    "docker--project-case-study": "/resources/read/docker-project-case-study",
    "docker--real-world-case-study": "/resources/read/docker-real-world-case-study",
    "docker--best-practices": "/resources/read/docker-best-practices",
    "docker--common-mistakes": "/resources/read/docker-common-mistakes",
    "docker--frequently-asked-questions": "/resources/read/docker-frequently-asked-questions",
    "docker--learning-roadmap": "/resources/read/docker-learning-roadmap",
    "docker--tips-tricks": "/resources/read/docker-tips-tricks",
    "docker--advanced-concepts": "/resources/read/docker-advanced-concepts",
    "docker--glossary": "/resources/read/docker-glossary",
    "docker--reference-guide": "/resources/read/docker-reference-guide",
    "power-bi--beginner-guide": "/resources/read/power-bi-beginner-guide",
    "power-bi--complete-tutorial": "/resources/read/power-bi-complete-tutorial",
    "power-bi--step-by-step-learning-guide": "/resources/read/power-bi-step-by-step-learning-guide",
    "power-bi--pdf-notes": "/resources/read/power-bi-pdf-notes",
    "power-bi--quick-revision-notes": "/resources/read/power-bi-quick-revision-notes",
    "power-bi--cheat-sheet": "/resources/read/power-bi-cheat-sheet",
    "power-bi--interview-questions": "/resources/read/power-bi-interview-questions",
    "power-bi--practice-questions": "/resources/read/power-bi-practice-questions",
    "power-bi--answer-key": "/resources/read/power-bi-answer-key",
    "power-bi--sample-exercises": "/resources/read/power-bi-sample-exercises",
    "power-bi--project-guide": "/resources/read/power-bi-project-guide",
    "power-bi--project-case-study": "/resources/read/power-bi-project-case-study",
    "power-bi--real-world-case-study": "/resources/read/power-bi-real-world-case-study",
    "power-bi--best-practices": "/resources/read/power-bi-best-practices",
    "power-bi--common-mistakes": "/resources/read/power-bi-common-mistakes",
    "power-bi--frequently-asked-questions": "/resources/read/power-bi-frequently-asked-questions",
    "power-bi--learning-roadmap": "/resources/read/power-bi-learning-roadmap",
    "power-bi--tips-tricks": "/resources/read/power-bi-tips-tricks",
    "power-bi--advanced-concepts": "/resources/read/power-bi-advanced-concepts",
    "power-bi--glossary": "/resources/read/power-bi-glossary",
    "power-bi--reference-guide": "/resources/read/power-bi-reference-guide",
    "tableau--beginner-guide": "/resources/read/tableau-beginner-guide",
    "tableau--complete-tutorial": "/resources/read/tableau-complete-tutorial",
    "tableau--step-by-step-learning-guide": "/resources/read/tableau-step-by-step-learning-guide",
    "tableau--pdf-notes": "/resources/read/tableau-pdf-notes",
    "tableau--quick-revision-notes": "/resources/read/tableau-quick-revision-notes",
    "tableau--cheat-sheet": "/resources/read/tableau-cheat-sheet",
    "tableau--interview-questions": "/resources/read/tableau-interview-questions",
    "tableau--practice-questions": "/resources/read/tableau-practice-questions",
    "tableau--answer-key": "/resources/read/tableau-answer-key",
    "tableau--sample-exercises": "/resources/read/tableau-sample-exercises",
    "tableau--project-guide": "/resources/read/tableau-project-guide",
    "tableau--project-case-study": "/resources/read/tableau-project-case-study",
    "tableau--real-world-case-study": "/resources/read/tableau-real-world-case-study",
    "tableau--best-practices": "/resources/read/tableau-best-practices",
    "tableau--common-mistakes": "/resources/read/tableau-common-mistakes",
    "tableau--frequently-asked-questions": "/resources/read/tableau-frequently-asked-questions",
    "tableau--learning-roadmap": "/resources/read/tableau-learning-roadmap",
    "tableau--tips-tricks": "/resources/read/tableau-tips-tricks",
    "tableau--advanced-concepts": "/resources/read/tableau-advanced-concepts",
    "tableau--glossary": "/resources/read/tableau-glossary",
    "tableau--reference-guide": "/resources/read/tableau-reference-guide",
};

export function getResourceReaderPath(id: string): string | null {
  return READER_ROUTES[id] ?? null;
}

