// Static catalog for the AI Mock Test Center. Scalable: add new categories here.
export type MockTestCategory = {
  id: string;
  name: string;
  emoji: string;
  description: string;
  subtopics: string[];
  difficulty: "easy" | "medium" | "hard" | "mixed";
  durationMinutes: number;
  questionCount: number;
  gradient: string;
};

export const MOCK_TEST_CATEGORIES: MockTestCategory[] = [
  {
    id: "aptitude",
    name: "Aptitude Test",
    emoji: "🧠",
    description: "Quantitative aptitude, arithmetic and data interpretation.",
    subtopics: [
      "Quantitative Aptitude",
      "Number System",
      "Percentages",
      "Profit & Loss",
      "Time & Work",
      "Time & Distance",
      "Probability",
      "Data Interpretation",
    ],
    difficulty: "mixed",
    durationMinutes: 30,
    questionCount: 30,
    gradient: "from-sky-500/20 to-indigo-500/10",
  },
  {
    id: "logical-reasoning",
    name: "Logical Reasoning",
    emoji: "🧩",
    description: "Patterns, puzzles and analytical thinking.",
    subtopics: [
      "Patterns",
      "Series",
      "Coding-Decoding",
      "Blood Relations",
      "Direction Sense",
      "Seating Arrangement",
      "Puzzles",
      "Analytical Reasoning",
    ],
    difficulty: "mixed",
    durationMinutes: 30,
    questionCount: 30,
    gradient: "from-violet-500/20 to-fuchsia-500/10",
  },
  {
    id: "general-knowledge",
    name: "General Knowledge",
    emoji: "💡",
    description: "Science, history, geography and current affairs.",
    subtopics: [
      "Science",
      "Technology",
      "Space",
      "Environment",
      "History",
      "Geography",
      "Indian Constitution",
      "Current Affairs",
    ],
    difficulty: "mixed",
    durationMinutes: 25,
    questionCount: 30,
    gradient: "from-emerald-500/20 to-teal-500/10",
  },
  {
    id: "computer-fundamentals",
    name: "Computer Fundamentals",
    emoji: "💻",
    description: "Hardware, software, OS and networking basics.",
    subtopics: [
      "Computer Basics",
      "Hardware",
      "Software",
      "Operating Systems",
      "Internet",
      "Networking",
      "Cyber Safety",
      "MS Office",
    ],
    difficulty: "easy",
    durationMinutes: 25,
    questionCount: 30,
    gradient: "from-blue-500/20 to-cyan-500/10",
  },
  {
    id: "programming-fundamentals",
    name: "Programming Fundamentals",
    emoji: "🌐",
    description: "Core programming concepts across popular languages.",
    subtopics: [
      "Python",
      "C",
      "C++",
      "Java",
      "JavaScript",
      "HTML",
      "CSS",
      "SQL",
      "Programming Logic",
    ],
    difficulty: "medium",
    durationMinutes: 30,
    questionCount: 30,
    gradient: "from-amber-500/20 to-orange-500/10",
  },
  {
    id: "ai-technology",
    name: "AI & Technology",
    emoji: "🤖",
    description: "AI, ML, cloud, cybersecurity and digital skills.",
    subtopics: [
      "Artificial Intelligence",
      "Machine Learning",
      "Data Science",
      "Cloud Computing",
      "Cyber Security",
      "Robotics",
      "Digital Skills",
    ],
    difficulty: "medium",
    durationMinutes: 30,
    questionCount: 30,
    gradient: "from-pink-500/20 to-rose-500/10",
  },
  {
    id: "school-class-10",
    name: "Class 10 Mock Test",
    emoji: "🎓",
    description: "Board-aligned mock test for Class 10 (CBSE / ICSE / State).",
    subtopics: ["Mathematics", "Science", "Social Science", "English", "General Knowledge"],
    difficulty: "medium",
    durationMinutes: 30,
    questionCount: 30,
    gradient: "from-green-500/20 to-lime-500/10",
  },
  {
    id: "school-class-11",
    name: "Class 11 Mock Test",
    emoji: "🎓",
    description: "Board-aligned mock test for Class 11 (CBSE / ICSE / State).",
    subtopics: ["Physics", "Chemistry", "Mathematics", "Biology", "English", "Reasoning"],
    difficulty: "medium",
    durationMinutes: 30,
    questionCount: 30,
    gradient: "from-teal-500/20 to-emerald-500/10",
  },
  {
    id: "school-class-12",
    name: "Class 12 Mock Test",
    emoji: "🎓",
    description: "Board-aligned mock test for Class 12 (CBSE / ICSE / State).",
    subtopics: ["Physics", "Chemistry", "Mathematics", "Biology", "English", "Reasoning"],
    difficulty: "hard",
    durationMinutes: 30,
    questionCount: 30,
    gradient: "from-indigo-500/20 to-blue-500/10",
  },
  {
    id: "placement-prep",
    name: "Placement Preparation",
    emoji: "💼",
    description: "Aptitude, reasoning, technical MCQs and interview readiness.",
    subtopics: [
      "Aptitude",
      "Logical Reasoning",
      "Technical MCQs",
      "Communication Skills",
      "Interview Readiness",
    ],
    difficulty: "hard",
    durationMinutes: 35,
    questionCount: 30,
    gradient: "from-rose-500/20 to-red-500/10",
  },
];

export function getMockTestCategory(id: string): MockTestCategory | undefined {
  return MOCK_TEST_CATEGORIES.find((c) => c.id === id);
}
